### ISSUE TITLE
AnyHttpUrl behaves differently when inherited from BaseSettings than from BaseModel

### ISSUE THREAD

**Issue by Zer0x00** [pydantic/pydantic-settings#104]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

AnyHttpUrl adds a trailing slash at the end of the URL.
Since this worked in Pydantic v1 and is different from Pydantic v2's BaseModel behaviour I guess this is unwanted.

### Example Code
```python3
############################################################
# Using BaseSettings the assertion fails:

from pydantic import AnyHttpUrl
from pydantic_settings import BaseSettings


class SettingsV2(BaseSettings):
    URL: AnyHttpUrl = "https://github.com"


settings_v2 = SettingsV2()

assert str(settings_v2.URL) == "https://github.com"

############################################################
# Using BaseModel works as expected:

from pydantic import AnyHttpUrl, BaseModel


class SettingsV2_BaseModel(BaseModel):
    URL: AnyHttpUrl = "https://github.com"


settings_base_model = SettingsV2_BaseModel()

assert str(settings_base_model.URL) == "https://github.com"

############################################################
# Pydantic v1 BaseSettings worked also as expected:
from pydantic import v1 as pydantic_v1


class SettingsV1(pydantic_v1.BaseSettings):
    URL: pydantic_v1.AnyHttpUrl = "https://github.com"


settings_v1 = SettingsV1()

assert str(settings_v1.URL) == "https://github.com"

```

### Python, Pydantic & OS Version
```
             pydantic version: 2.0.1
        pydantic-core version: 2.0.2 release build profile
                 install path: /usr/local/lib/python3.11/dist-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @Zer0x00 for reporting this 🙏 

In `pydantic-settings`, [validate_default config](https://docs.pydantic.dev/latest/usage/fields/#validate-default-values) is enabled by default. So, that's why you get a trailing slash at the end of the URL.

You can disable this:

```py
from pydantic import AnyHttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict


class SettingsV2(BaseSettings):
    model_config = SettingsConfigDict(validate_default=False)  # disablin the behavior

    URL: AnyHttpUrl = "https://github.com"


settings_v2 = SettingsV2()

assert str(settings_v2.URL) == "https://github.com"
```

**Comment by Zer0x00** [comment]
Thanks for the hint but I wonder if the default value of `validate_default_config` shouldn't match the default of Pydantic BaseModel?

**Comment by samuelcolvin** [comment]
No, it's extremely helpful to have the default values validated with `BaseSettings` - it's useful to be able to access `settings_base_model.URL.host` whether or not that field was set during validation.

Whereas with `BaseModel` it's generally preferable to reduce the overhead by not running validation on defaults, this is also how V1 behaved. The URL validation has changed/improved significantly in V2, hence the trailing slash.

**Comment by shawnwall** [comment]
noting this may be the cause of a CORS origin error I've run into when migrating to `pydantic-settings`, as, to my knowledge, these origins should _not_ contain a trailing slash, and now it is being added.

**Comment by sultaniman** [comment]
Indeed when used to pass values to CORS middleware we get trailing slashes which then breaks request pre-flight
https://github.com/encode/starlette/discussions/2735
