### ISSUE TITLE
DotEnv ValueError when env variable name is shorter than env_prefix

### ISSUE THREAD

**Issue by jvllmr** [pydantic/pydantic-settings#106]
Example:

```
class DramatiqSettings(BaseSettings):
    broker_url: RedisDsn

    model_config = SettingsConfigDict(
        env_file=".env", env_prefix="plato_worker_", extra="ignore"  # type: ignore
    )
```
I also have another settings class that holds my general application settings.

When processing my PLATO_DEBUG env var, the following line fails:
https://github.com/pydantic/pydantic-settings/blob/373af71ae8ac0d2c3530857ce51ef28c9e9178d2/pydantic_settings/sources.py#L583

```
ValueError: not enough values to unpack (expected at least 1, got 0)
```

It's because PLATO_DEBUG is shorter than the env_prefix for my DramatiqSettings class.

Possible Solution:
Check if the env var name actually starts with the env prefix before stripping the name.

Selected Assignee: @samuelcolvin

**Comment by jvllmr** [comment]
I realised that this also happens when extras are forbidden

**Comment by hramezani** [comment]
Thanks @jvllmr for reporting this 🙏 

Would you mind opening a PR for fixing this? otherwise, I will fix it.
