### ISSUE TITLE
pylance complaining about missing paramters while instantiating 

### ISSUE THREAD

**Issue by jiaulislam** [pydantic/pydantic-settings#108]
on Pydantic v1 i used to solve this problem with parse_obj method but now that method is deprecated. How should this  be instantiated ? 

Thanks in advance. 

![image](https://github.com/pydantic/pydantic-settings/assets/54698236/fa2bd31d-e507-4cf5-91a1-cb822ce15b7b)

Selected Assignee: @dmontagu

**Comment by hramezani** [comment]
Thanks @jiaulislam for reporting this issue 🙏 

Please let us know what version of `Pydantic` and `pydantic-settings` are you using?

**Comment by jiaulislam** [comment]
> 

![image](https://github.com/pydantic/pydantic-settings/assets/54698236/59c4bc74-2b47-4b34-97f2-fe1e0bb99b01)

**Comment by hramezani** [comment]
Pylance uses [Pyright](https://github.com/microsoft/pyright) for type checking.
There is an issue in [pyright](https://github.com/microsoft/pyright/issues/4556) regarding this.


You probably can make your fields `Optional` or add some default value for them to fix this.

**Comment by agucova** [comment]
@hramezani I can replicate this issue, and it's not just a Pyright problem, the error manifests at runtime:

```python
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    test: str
    
settings = Settings()
```

Gives:
```shell
$ python3 test_settings.py
Traceback (most recent call last):
  File "test_settings.py", line 7, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "python3.11/site-packages/pydantic_settings/main.py", line 61, in __init__
    super().__init__(
  File "python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
test
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
```

I'm using pydantic 2.0.2 and pydantic-settings 2.0.1.

**Comment by samuelcolvin** [comment]
Use `model_validate()` which has the same use case as `parse_obj()`.
