### ISSUE TITLE
Extra.Forbid is not applied when using BaseSettings with Config.env_file defined

### ISSUE THREAD

**Issue by jberthier-ma** [pydantic/pydantic-settings#11]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Reading the documentation and as BaseSettings inherits from BaseModel it'd be expected to have `Config.extra` parameters working when `Config.env_file` is defined.

It appears that without Config.env files it works as expected, but when it comes from env_files the extra config is ignored.

If this is expected I can make a PR to make the documentation more explicit on this specific point.

### Example Code

```Python
from pydantic import BaseSettings, Extra

""""
# .env.test
title="cool stuff"
other=42
"""

class Plop(BaseSettings):
    title: str

    class Config:
        extra: Extra = Extra.forbid
        env_file = ".env.test"

Plop()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: .venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Oct 24 2022, 19:55:51) [GCC 9.4.0]
                     platform: Linux-5.17.0-051700-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Good catch, thanks for reporting. Realistically this won't be changed in pydantic v1.10, but we should make sure it's fixed in pydantic V2 where settings will become a separate package which uses `pydantic`.

**Comment by hramezani** [comment]
@samuelcolvin Is it really a bug? It seems we loop over settings fields and collect the value for the fields from file or environment variables. So, we won't get the extra value provided in the file. Am I wrong?

**Comment by samuelcolvin** [comment]
I haven't actually tried it.

We need to check the current behaviour then decide if it's correct or needs changing.

**Comment by hramezani** [comment]
Currently we loop over fields and collect the values. If we are going to change the behavior, we need to collect the envs and then initialize the model. Then the default behavior(collect envs from environment without prefix) will be tricky because if we define a model with a field named `test_field`, then the other environment variables are extra. We may need to change it just for dotenv file or prefixed envs

**Comment by hramezani** [comment]
OK, that needs to be changed and documented
