### ISSUE TITLE
Add documentation 

### ISSUE THREAD

**Issue by urbanonymous** [pydantic/pydantic-settings#115]
A how to use quick demo in the readme would be useful

i.e. how is it installed + imported + used (you have already the docs md, link it at least)

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @urbanonymous for reporting this 🙏 

We have documentation for `pydantic-settings` in https://docs.pydantic.dev/latest/usage/pydantic_settings/

I've created a [PR](https://github.com/pydantic/pydantic-settings/pull/121) to add documentation link to `README.md`

**Comment by hramezani** [comment]
Closed in https://github.com/pydantic/pydantic-settings/commit/5912eb07238239e523eaccdc5635184c77c887a9
