### ISSUE TITLE
Is there a gradual upgrade path from Pydantic v1 to v2 for BaseSettings?

### ISSUE THREAD

**Issue by vdwees** [pydantic/pydantic-settings#117]
Posting the question in case someone else is also dealing with it.

I have about 3 years of code based on top of Pydantic v1, so I'd like to be able to migrate to v2 in stages. Pydantic v2 did a great job of not breaking very much (preferring deprecation warnings where possible), so this seems mostly feasible. 

So far, BaseSettings is the one exception to this. BaseSettings is now in this separate package, **but it depends on v2**. So I have to choose between Pydantic v1 **or** Pydantic v2.

In order to support both, I intend to create my own Settings module to abstract this break. Am I missing something?

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @vdwees for this issue 🙏 

Great to hear that you are using Pydantic and are going to migrate to V2.

> In order to support both, I intend to create my own Settings module to abstract this break. Am I missing something?

Sounds good. I would suggest upgrading to V2 as soon as possible.

Note: We included the latest Pydantic V1 in Pydantic V2 and you can only install Pydantic v2 and use both.

For example you can install `pydantic-settings` which depends on `Pydantic V2` and use `BaseSettings` from V1 and V2 like:

```py
from pydantic_settings import BaseSettings  # V2
from pydantic.v1 import BaseSettings  # V1
```

**Comment by vdwees** [comment]
This is what I missed:
`from pydantic.v1 import BaseSettings  # V1`
Thanks for the tip!
