### ISSUE TITLE
Support for Configuration file loading?

### ISSUE THREAD

**Issue by jordantshaw** [pydantic/pydantic-settings#13]
@samuelcolvin do you plan to add support for configuration file loading?  Such as being able to load settings from toml, json, ini, etc.. files?  I would be interested in contributing  to this effort if possible.

**Comment by einali** [comment]
I think toml will be de facto standard for python setting as standard library support from 3.11.

**Comment by hramezani** [comment]
It is possible to have your custom source class in the new `pydantic-settings`.

FYI, pydantic-settings now is a separate package and is in alpha state. you can install it by `pip install pydantic-settings --pre` and test it.

Please take a look at [customise settings sources section of doc](https://github.com/pydantic/pydantic-settings/blob/main/docs/index.md#customise-settings-sources).
