### ISSUE TITLE
mypy error when using `_env_file` in BaseSettings sub-class

### ISSUE THREAD

**Issue by duckontheweb** [pydantic/pydantic-settings#131]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/jduckworth/.pyenv/versions/3.8.9/envs/mlhub-backend-dev/lib/python3.8/site-packages/pydantic
               python version: 3.8.9 (default, Apr 23 2021, 14:38:08)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

Running `mypy --show-error-codes ./pydantic_mypy_error.py` with the files shown below gives the following error:

```
pydantic_mypy_error.py:9: error: Unexpected keyword argument "_env_file" for "EnvFileBaseSettings"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

### `mypy.ini`

```
[mypy]
plugins = pydantic.mypy
```

### `pydantic_mypy_error.py`

```python

from pydantic import BaseSettings


class EnvFileBaseSettings(BaseSettings):
    my_var: str


if __name__ == "__main__":
    _ = EnvFileBaseSettings(_env_file=".test.env")
```

### `.test.env`
```
# .test.env
MY_VAR=thing
```

Selected Assignee: @davidhewitt

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
We created a [PR](https://github.com/pydantic/pydantic/pull/6760) to fix the problem.

Please install Pydantic from that branch and test it.

**Comment by johnthagen** [comment]
@hramezani I can confirm that when pointing to Poetry at

```toml
pydantic = { git = "https://github.com/pydantic/pydantic.git", branch = "main" }
```

That the this issue has been resolved. Thank you.

**Comment by hramezani** [comment]
Thanks @johnthagen for the feedback
