### ISSUE TITLE
Pydantic-settings core to Rust

### ISSUE THREAD

**Issue by dariocurr** [pydantic/pydantic-settings#134]
Hi guys. I am Dario, a technical PO from [hiop](https://github.com/hiop-io).

First of all I wanted to thank you guys for the great work you do.

I recently started to develop a Rust equivalent of `BaseSettings` because I love it and use it a lot when I develop in Python: the crate name in [env-settings](https://crates.io/crates/env-settings)

I am currently working on adding features that are present in your `BaseSettings`.

I wonder if you also want to convert `pydantic-settings` core to Rust, as you did with `pydantic`.
If so, I would be very happy to help and would be honored if my `env-settings` would be the starting point of such conversion.

So I wanted to know if you would be interested in it and if you think we can contribute together to such change

Selected Assignee: @samuelcolvin

**Comment by samuelcolvin** [comment]
I don't think it makes any sense to implement pydantic-settings' extra behaviour in rust since it's not performance critical.

Since pydantic-settings already used pydantic and thereby pydantic-core, its validation is already implemented in Rust.
