### ISSUE TITLE
Using single underscore as `env_nested_delimiter`

### ISSUE THREAD

**Issue by egormkn** [pydantic/pydantic-settings#137]
I am trying to use submodels to group related environment variables together. For example, it seems convenient to define 

```python
class UserSettings(BaseModel):
    email: str = ""
    password: str = ""
    
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_nested_delimiter="_")

    user: UserSettings
```

and use `USER_NAME` and `USER_PASSWORD` to specify values. Single underscore as a delimiter also allows to specify environment variables that are used by third-party libraries:

```python
class SentrySettings(BaseModel):
    dsn: str  # Initialized from SENTRY_DSN
    # other Sentry configuration here...
    
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_nested_delimiter="_")

    sentry: SentrySettings
```

However, there are several problems with this approach:

1) I didn't find a way to explicitly ignore invalid values. In the first example above Pydantic tries to parse the user field from the `USER` environment variable defined in Linux and throws 
```pydantic_settings.sources.SettingsError: error parsing value for field "user" from source "EnvSettingsSource"```
as that is not a valid json. I suggest to allow to explicitly disable parsing a submodel from a json (as `USER`) and initialize it using individual submodel fields (as `USER_NAME` and `USER_PASSWORD`).

2) There is a bug with fields that include delimiter character in their name:

    ```python
    import os
    
    from pydantic import BaseModel
    from pydantic_settings import BaseSettings, SettingsConfigDict
    
    os.environ["FIELD_VALUE"] = "Field value"
    os.environ["ANOTHER_FIELD_VALUE"] = "Another field value"
    
    
    class FieldSettings(BaseModel):
        value: str = ""
    
    
    class AnotherFieldSettings(BaseModel):
        value: str = ""
    
    
    class Settings(BaseSettings):
        model_config = SettingsConfigDict(env_nested_delimiter="_")
    
        field: FieldSettings
        another_field: AnotherFieldSettings
    
    
    settings = Settings()
    
    print(settings.field.value)  # "Field value"
    print(settings.another_field.value)  # ""
    ```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
related to https://github.com/pydantic/pydantic-settings/issues/51
