### ISSUE TITLE
`populate_by_name` and `env_prefix` are ignored when alias is used

### ISSUE THREAD

**Issue by wikiped** [pydantic/pydantic-settings#144]
Given this code:

```python
from pydantic import BaseModel, FilePath
from pydantic.alias_generators import to_pascal
from pydantic_settings import BaseSettings
import os


os.environ['abc'] = 'should_not_be_read'


class Settings(BaseSettings,
               populate_by_name=True,
               alias_generator=to_pascal,
               extra='forbid',
               env_prefix='test_'):    
    abc: FilePath


class Model(BaseModel,
            populate_by_name=True,
            alias_generator=to_pascal,
            extra='forbid',
            env_prefix='test_'):    
    abc: FilePath


abc = FilePath('c:/bootmgr')
abc.is_file()  # True

m = Model(abc=abc)

print(Settings.model_config['env_prefix'])  # 'test_'

print(Settings.model_config['populate_by_name'])  # True

s = Settings(abc=abc)
```

It is expected that it will run without errors.

However the last line throws:

<details><summary>Traceback</summary>

```shell
Traceback (most recent call last):
  File "C:\Python\Test\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-1fc3f78be550>", line 1, in <module>
    s = Settings(abc=abc)
        ^^^^^^^^^^^^^^^^^
  File "C:\Python\Test\.venv\Lib\site-packages\pydantic_settings\main.py", line 71, in __init__
    super().__init__(
  File "C:\Python\Test\.venv\Lib\site-packages\pydantic\main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
Abc
  Path does not point to a file [type=path_not_file, input_value='should_not_be_read', input_type=str]
abc
  Extra inputs are not permitted [type=extra_forbidden, input_value=WindowsPath('c:/bootmgr'), input_type=WindowsPath]
    For further information visit https://errors.pydantic.dev/2.1/v/extra_forbidden
```

</details>

Note that environment var `abc` has been read, while it should not have been, therefore ignoring given `env_prefix`:

```shell
Abc
  Path does not point to a file [type=path_not_file, input_value='should_not_be_read', input_type=str]
```

and although `populate_by_name=True`, it was ignored:

```shell
abc
  Extra inputs are not permitted [type=extra_forbidden, input_value=WindowsPath('c:/bootmgr'), input_type=WindowsPath]
    For further information visit https://errors.pydantic.dev/2.1/v/extra_forbidden
```

While `Model` did not raise any errors.

Without `alias_generator` argument `Settings` also does not raise errors.

<details><summary>Versions Info:</summary>

```shell
In [6]: import sys; print('Python %s on %s' % (sys.version, sys.platform))
Out[7]: Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32

In [8]: from pydantic_settings import __version__
In [9]: __version__
Out[9]: '2.0.3'

In [10]: from pydantic import __version__
In [11]: __version__
Out[11]: '2.1.1'
```

</details>

**Comment by wikiped** [comment]
It seems like an easy fix for the `env_prefix` issue is to replace [`_apply_case_sensitive`](https://github.com/pydantic/pydantic-settings/blob/6f12222d8a0c75162167c13a4bb2af5a81b94401/pydantic_settings/sources.py#L137C5-L138C67) with:

```python
    def _apply_case_sensitive(self, value: str) -> str:
        value = self._trasform_env_alias(value)
        return value.lower() if not self.case_sensitive else value

    def _trasform_env_alias(self, value: str) -> str:
        if self.env_prefix:
            return f'{self.env_prefix}{value}'
        return value
```

But a proper ifx would probably best be a reversed:

```python
    def _apply_case_sensitive(self, value: str) -> str:
        return value.lower() if not self.case_sensitive else value

    def _trasform_env_alias(self, value: str) -> str:
        value = self._apply_case_sensitive(value)
        if self.env_prefix:
            return f'{self.env_prefix}{value}'
        return value
```

With replacing references to `_apply_case_sensitive` in `_extract_field_info` with `_trasform_env_alias`

**Comment by wikiped** [comment]
The issue with with `populate_by_name` being ignored seems to be somewhat more complicated.

One way to fix it would be to make all subclasses of `PydanticBaseSettingsSource` to conform to the same protocol for their `__call__` method. Which should return a mapping of `field_name: field_value` and not current: `field_alias | field_name: field_value`.

This would help to avoid the situation when result of `deep_update` looks like:

```
{
    'Abc': 'value_from_one_source',
    'abc': 'value_from_another_source'
}
```

which causes the error shown in the original post.

**Comment by hramezani** [comment]
Thanks @wikiped for reporting this 🙏 

`env_prefix` does not apply to fields with the alias. take a look at the `auth_key` field in [first example of doc](https://docs.pydantic.dev/latest/usage/pydantic_settings/). Also, [we have a test for this behaviour](https://github.com/pydantic/pydantic-settings/blob/6f12222d8a0c75162167c13a4bb2af5a81b94401/tests/test_settings.py#L507)

The `Settings` model has `alias_generator=to_pascal`. So, `abc` has the alias `Abc`. you can find it by:
```
print(Settings.model_fields['abc'])
> # annotation=Path required=True alias='Abc' alias_priority=1 metadata=[PathType(path_type='file')] 
```

Then pydantic-settings looks for field alias(Abc) and as you set the `abc` in the initialization `s = Settings(abc=abc)` and `populate_by_name=True`, So you will see the validation error.

I will create a PR to document this.

**Comment by wikiped** [comment]
Thanks for response @hramezani 

I see the issue was with the expectation to have a drop-in replacement for `BaseModel` rather than with the package.

Well, looks like to meet the expectations all relevant sources need to be customized and supplied to `settings_customise_sources`.
