### ISSUE TITLE
python-dotenv should be optional

### ISSUE THREAD

**Issue by maxzhenzhera** [pydantic/pydantic-settings#149]
From `pyproject.toml`:
```
requires-python = '>=3.7'
dependencies = [
    'pydantic>=2.0.1',
    'python-dotenv>=0.21.0',
]
dynamic = ['version']
```
`python-dotenv` is always installed.

From `pydantic_settings.sources`:
https://github.com/pydantic/pydantic-settings/blob/919a20b77527ecc1cd6eeb0a09ca22cc21486fb8/pydantic_settings/sources.py#L620-L632
- here is the logic of the optional `python-dotenv`
- and the wrong message in exception to install as pydantic extra (which already does not have this extra)

---

One more place where the project depends on `python-dotenv` is `tests.test_settings`:
https://github.com/pydantic/pydantic-settings/blob/919a20b77527ecc1cd6eeb0a09ca22cc21486fb8/tests/test_settings.py#L39-L42
~~But even here checks are made to skip tests if `python-dotenv` is not installed (one of the tests with such a check):~~
https://github.com/pydantic/pydantic-settings/blob/919a20b77527ecc1cd6eeb0a09ca22cc21486fb8/tests/test_settings.py#L663-L680
While making PR I understood the reason for making it in tests.
Finally, I changed the CI workflow.

Selected Assignee: @dmontagu

**Comment by samuelcolvin** [comment]
Why not keep `python-dotenv` as required dependency and remove the error handling?

I mean it was different before where pydantic was used for many applications which didn't require use of `Settings`.

If there's a good reason to make it optional, I'd be happy to consider it - but my first reaction is that the requirement should not be optional and we just change the code that assumes it is.

**Comment by maxzhenzhera** [comment]
Personally, I do not use `.env` files.
So, I never load it using `pydantic-settings` and therefore code that depends on `python-dotenv` is never executed.

Yep, obviously, I can not say that `python-dotenv` is kind of heavy dependency and it bothers me.
Just in my case, it is unused  and without it, my dependencies will become a little bit cleaner.

**Comment by hramezani** [comment]
related code for optional dotenv removed at https://github.com/pydantic/pydantic-settings/commit/0226fe2deab7896a952f6b7a53dd13d92c8a5540
