### ISSUE TITLE
mypy complains whn instantiating a settings object

### ISSUE THREAD

**Issue by vladdu** [pydantic/pydantic-settings#164]
Hi! I couldn't find any other mention of this, so probably I'm doing something wrong.

I have a settings class inheriting from BaseSettings, and when instantiating it with a no-parameter constructor, mypy complains that arguments are missing. Is this something that the pydantic.mypy plugin handles? Unfortunately, I can't use that, because for some reason it makes mypy crash. Is there another workaround than providing dummy default values for everything?

**Comment by hramezani** [comment]
Hi @vladdu,

Thanks for reporting this issue 🙏 

Yes, The only possible way to fix mypy error is [using pydantic mypy plugin](https://docs.pydantic.dev/latest/integrations/mypy/)

**Comment by dmontagu** [comment]
@vladdu if you can share some more details about your crash we can look into it and try to resolve it

**Comment by tshipenchko** [comment]
I confirm that [using pydantic mypy plugin](https://docs.pydantic.dev/latest/integrations/mypy/) fixes the issue
```commandline
$ mypy app/cli/__main__.py  # without plugin
app/cli/__main__.py:18: error: Missing named argument "bot_token" for "Config"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
$ mypy app/cli/__main__.py  # with plugin
Success: no issues found in 1 source file
```
My `pyproject.toml`:
```toml
[tool.mypy]
plugins = ["pydantic.mypy"]
```
