### ISSUE TITLE
BaseSetting uses env alias as default value instead of the set variable

### ISSUE THREAD

**Issue by akoshel** [pydantic/pydantic-settings#167]
Hi! 
BaseSetting uses env alias as default value instead of the set variable

```
>>> from pydantic_settings import BaseSettings
>>> 
>>> print(pydantic_settings.__version__)
2.0.3
>>> 
>>> os.environ["P"] = "P"
>>> 
>>> 
>>> def get_my_value(e: str) -> str:
...   return "123"
... 
>>> default_p = get_my_value(os.environ["P"])
>>> 
>>> 
>>> class Example1(BaseSettings):
...   p: str = default_p
... 
>>> 
>>> 
>>> class Example2(BaseSettings):
...   e: str = default_p
... 
>>> print(Example1())
p='P'
>>> print(Example2())
e='123'
>>> 
```

**Comment by hramezani** [comment]
Hi @akoshel 👋 

`Example1` has `p` as a field. So, `pydantic-settigns` collect value for `p` from env variable `P`.
`Example1` has `e` as a field. As we don't have env variable `e` or `E`, the default value `123` will be set for `e`

**Comment by akoshel** [comment]
Hi! @hramezani 
This behavior is quite unclear. In my opinion, the value set by the developer should take precedence over the environment alias. Currently, it simply ignores the set value, making it challenging to debug.

**Comment by hramezani** [comment]
This is a clear and [documented](https://docs.pydantic.dev/latest/usage/pydantic_settings/#field-value-priority) behavior.

You can change the priority by [overriding the `settings_customise_sources` classmethod](https://docs.pydantic.dev/latest/usage/pydantic_settings/#changing-priority).
