### ISSUE TITLE
Inconsistent applying annotated BeforeValidator 

### ISSUE THREAD

**Issue by valq7711** [pydantic/pydantic-settings#184]
Related to #157 
I think `before` is quite clear that it must be applied __before__ (not after) any validation

> Or, you can change the env variable value in .env to a valid json like:

Sorry, but If I have a valid json, I can use just regular pydantic model and pass a valid json to it, so why I ever need this package? 

Suggested solution using `settings_customise_sources` to override single field parsing looks monstrosity.

Please parse the signature of the first `BeforeValidator` and if it expects `str`  (or some special `str`-derived type like `class RawStr(str)`) then pass the field value as is.
Or introduce something like `RawValidator`

**Comment by hramezani** [comment]
> Sorry, but If I have a valid json, I can use just regular pydantic model and pass a valid json to it, so why I ever need this package?

This is the only thing that `pydantic-settings` does. reading the value and preparing(parsing) them and passing them to `pydantic`. `pydantic-settings` does it for different sources and parses the complex value even for the nested fields.
If you only have one source and your values are not complex, you may don't need to use `pydantic-settings`


 > Suggested solution using settings_customise_sources to override single field parsing looks monstrosity.

Agree that the amount of code for doing a simple customization like this is too much. we need to improve it. but the only custom code is 
```py
class MyDotEnvSettingsSource(DotEnvSettingsSource):
    def prepare_field_value(self, field_name: str, field: FieldInfo, value: Any, value_is_complex: bool) -> Any:
        return value
```

> Please parse the signature of the first BeforeValidator and if it expects str (or some special str-derived type like class RawStr(str)) then pass the field value as is.
Or introduce something like RawValidator

That would be an idea and probably works. I would be happy to review a patch. So, if you have time and are interested on this  feel free to submit a patch.
