### ISSUE TITLE
What is the best Practices for YAML Configuration Loading

### ISSUE THREAD

**Issue by yinzixie** [pydantic/pydantic-settings#185]
I understand that the main purpose of pydantic-settings is to initialize settings model by reading from env file.

But I am facing a bit of confusion. 

My requirement is that I am not using an env file; instead, I wish to read configurations directly from a YAML file. In this context, I am wondering if I still need to use a custom source to achieve my goal. 

This is because I have noticed that I can actually build the settings directly by using `SettingsModel(**data)` after reading the YAML file with `yaml.safe_load`. 

What are the differences and advantages between using these two methods?

**Comment by hramezani** [comment]
Yeah, you can load the yaml file and build your settings by `SettingsModel(**data)`. This is working without a problem.

Also, as you mentioned you can have a custom settings source class for this purpose.

The first approach is easy to implement and you will lose some internal functionality of `pydantic-settings`. e.g. parsing complex values.

Consider the following setting model:

```py
    class Settings(BaseSettings):
        foo: Dict[int, str]
```
`pydantic-settings` will parse the value provided for `foo` in `env` of `dotenv` file and convert the value to a dict. e.g if you have `foo={1: 'bar'}` in env, `pydantic-settings` parses the value as a valid dict not str.

So, if you go with the first approach, probably you have to parse the value by yourself.
