### ISSUE TITLE
Please bring back env= to use it instead of alias to override envvar names for fields

### ISSUE THREAD

**Issue by espdev** [pydantic/pydantic-settings#186]
Hello!

I ran into an issue when using pydantic-settings with Pydantic v2.x. 

In Pydantic v1.x I can use `env='ENVVAR_NAME'` to specify the environment name that is not the same as the field name. Also in Pydantic v1.x `alias=` for this is not used and raises a warning:

https://github.com/pydantic/pydantic/blob/2e939dc3bfb88f54efb66f8f1a031ff22e4f9865/pydantic/env_settings.py#L101-L106

I think it's wise not to mix field aliases and environment variable names together. It's reasonable.

However, in Pydantic v2.x `alias` is being used again to override envvar names. What was this done for and what's wrong with `env`?

Back to my problem with Pydantic v2.x.

In my code I use yaml config files over pydantic settings models for flexible configuration management.
Here is a simple example.

I have a default typed config in Pydantic model:
```python
class Config(BaseSettings):
    foo: int = 10
    bar: str = Field("hello", env="BAR_1")
    spam: float = 1.0
    ...
```

And YAML file(s) where I can override the config values:
```yaml
foo: 20
bar: "ola"
```

In my code I load and merge the config from the default model and all config files something like this:
```python
config = Config.load(*all_my_config_files)
```

What's the problem with `alias`? If `alias=` is used instead of `env=` to override the envvar name, I need to change the field name in my config files!
```yaml:
foo: 20
bar_1: "ola"   # because in Pydantic v2.x we need to use alias=BAR_1 instead of env=BAR_1.
```

I don't want to override the field names in my files, but I still want to be able to set the name of an environment variable. It just breaks my configuration because there are two completely different entities mixing here.

What do you guys think about that? I'm hoping for your support.
Thanks.

**Comment by hramezani** [comment]
Hello @espdev ,

We decided to use `alias` instead of `env` because  `alias` does exactly the thing that `env` did. in your case, you want to be able to collect data for your field by `field_name` and another name. So, You can enable (populate_by_name)[https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name] config on your model to be able to collect field data by field name.

**Comment by espdev** [comment]
> So, You can enable populate_by_name

Good point, thanks! I will try this.
