### ISSUE TITLE
Feature Request: Make it possible to specify environment variables for fields again

### ISSUE THREAD

**Issue by palle-k** [pydantic/pydantic-settings#193]
With Pydantic 1.x, it was possible to set an env name to populate a field from, using `Field(..., env="SOME_ENV_VAR")`. This behavior was replaced in Pydantic-Settings with `Field(...validation_alias="some_var_name")`. However, the new approach does not allow specific environment variables to be loaded in nested settings:

```python
class NestedModel(BaseModel):
    foo: Annotated[str, Field(..., validation_alias="foo")]  # does not actually load "FOO", instead loads "NESTED__FOO"
    bar: str


class Settings(BaseSettings):
    nested: NestedModel

    model_config = SettingsConfigDict(env_nested_delimiter="__")
```

Here, I would like to populate `NestedModel.foo` from the environment variable `FOO`, while `NestedModel.bar` should be populated using the environment variable `NESTED__BAR`. However, as settings sources pre-process env variables using the nested delimiter, `NestedModel` cannot access `FOO` in any way. 

I would appreciate, if this behavior was possible again, i.e. if there was a way to source a field from any environment variable in a nested model, not just ones that are provided by applying `env_nested_delimiter`, like it was in Pydantic 1.x.

---

### Attempted Workarounds

Two workarounds have been attempted, each having its own set of drawbacks.

#### Using BaseSettings for the nested model class

This workaround was able to target individual environment variables, as this created another "top-level", where I had access to any env variable. However, this approach has the drawback that `model_config` (and potentially `settings_customize_sources`) need to be duplicated across both the nested and root settings and that the nested model by default attempts to populate all fields itself from the environment directly, which can result in some conflicts if a field from the top level scope is named like a field from the nested scope (e.g. if there's an env var `FOO` and another env var `NESTED__FOO`)

#### Changing settings sources

This approach is rather messy, as multiple sources may needs to be modified to include the updated behavior. Furthermore, as the settings sources only have access to the top level fields, this approach is rather messy - e.g. when hooking into `explode_env_vars` to inject top-level variables into nested dictionaries and it suffers from the same drawback as the other approach.

**Comment by DanielHabenicht** [comment]
@palle-k was this implemented or did you find a better workaround than using `BaseSettings`?

**Comment by palle-k** [comment]
@DanielHabenicht we switched to using settings sources and using BaseSettings for the nested models.

**Comment by DanielHabenicht** [comment]
Alright, as it is not implemented are you interested in reopening the issue?
Also do you mind sharing your `CustomSource` implementation in the mean time?
