### ISSUE TITLE
What is the proper way to replicate `DotEnvSettingsSource` to read yaml files?

### ISSUE THREAD

**Issue by alexdashkov** [pydantic/pydantic-settings#202]
Hello,
I'm trying to make Pydantic settings capable to read configuration from the `yaml` files in the same manner, it's done for the `.env`.  For example I have a basic class like that: 

```python
from pydantic_settings import BaseSettings

class MyPerfectSettings(BaseSettings):
    some_variable_1: str
    some_variable_2: str
    some_variable_3: str

settings = MyPerfectSettings(_env_file=("base.env", "prod.env")
```
It works pretty well with the basic examples with the static path in the `model_config` property. However, I can't achieve a similar functionality as for `.env` files when you pass a tuple with `.env` files into the `__init__` method.
```python
class YamlBasedSettings(BaseModel):
    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        return (
            init_settings,
            # YamlConfigSettingsSource(settings_cls,  _yaml_files ???),  <--- How can I get this variable here? 
            env_settings,
            file_secret_settings,
        )
    @classmethod
    def from_env(cls, env) -> Self:
        ....
        return cls(_yaml_files=(base_yaml_settings, env_yaml_settings))
```

I see next problems: 
1. I can't properly set custom variable in the  `__init__` method to use it later as I'm getting an error about `__private_attributes__` and `__pydantic_private__`. Is there any documentation about how I can safely change it? 
2. Looks like `settings_customise_sources` method doesn't give me an access to the `self` (as it's a class method) so I don't have an access to the arguments passed into the `__init__` method. 

It looks like it should work if I overwrite the `_settings_build_values` function instead of `settings_customise_sources`, but it looks wrong as from my understanding `settings_customise_sources` should be able to handle all that (as it's mentioned like a hook for the customisation).

```python
class BaseYamlSettings(BaseSettings):
    def _settings_build_values(self, values, *args, **kwargs) -> dict[str, Any]:
        yaml_files = values.pop("__yaml_files")
        yaml_data = YamlConfigSettingsSource(self.__class__, yaml_files)()
        data = super()._settings_build_values(values, *args, **kwargs)
        return deep_update(yaml_data, data)
    @classmethod
    def from_env(cls, env) -> Self:
        return cls(__yaml_files=("base.yaml", f"{env}.yaml"))
```

All this time I have a feeling that I'm missing some very important part.

Could you advise me how to implement it in the proper way?

Thanks!

**Comment by hramezani** [comment]
Thanks @alexdashkov for reporting 👍 

All the things that you mentioned above are correct. and I think the best way (for now) to do it is overriding `_settings_build_values` which is not good IMO.

BTW, we probably need to rethink/redesign it later and make the setting class more flexible and customizable
