### ISSUE TITLE
Disable `env_prefix` with a `None` value

### ISSUE THREAD

**Issue by azmeuk** [pydantic/pydantic-settings#205]
I was migrating a custom settings class to pydantic-settings, and I encountered a surprising behavior with a `path` variable in a sub-class settings.

```python
>>> import os
... from pydantic_settings import BaseSettings
... from pydantic_settings import SettingsConfigDict
...
...
... class SubSettings(BaseSettings):
...     bar : str | None = None
...     path : str | None = None
...
...
... class Settings(BaseSettings):
...     model_config = SettingsConfigDict(env_nested_delimiter="__")
...
...     foo : str | None = None
...     sub : SubSettings | None = None
...
...
... os.environ["FOO"] = "FOO"
... os.environ["SUB__BAR"] = "BAR"
... config_obj = Settings()
... assert  config_obj.foo == "FOO"
... assert config_obj.sub.bar == "BAR"
... assert  config_obj.sub.path is None
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
AssertionError
```
Obviously, the `PATH` environment variable is always set and makes the assertion fail.

For compatibility reasons, I would like to keep that `path` var for the moment. 

I could solve the situation by inheriting `SubSettings` from `BaseModel` instead `BaseSettings`, but I understand that the two classes do not exactly behave the same, for example with default values validation.

I could also use an arbitrary `env_prefix` in `SubSettings` or an alias in the `path` field so I would be sure to not accidentally load the `PATH` environment variable, but that feels hacky.

I was thinking it would be convenient if `env_prefix` could be made `None`, so environment variable would not be loaded.

What do you think?

**Comment by hramezani** [comment]
Thanks @azmeuk for reporting this.

When you initialize `Settings` class, `pydantic-settings` collects data and passes them to the settings model. Then `pydantic` initializes every subfield. So, As your `SubSettings` class inherits from `BaseSettings` it will collect values for `path` from the environment variables.

You can fix the problem by changing `SubSettings` to inherit from `BaseModel` as [the example in the docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values)

**Comment by azmeuk** [comment]
> You can fix the problem by changing SubSettings to inherit from BaseModel as [the example in the docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values)

Indeed, I mention this in the initial post. However, as I understand, this would not have feature parity with `BaseSettings`, partly because of default values validation behaving differently on `BaseModel`. This is why I suggested a way to disable environment variables support in `BaseSettings`.

**Comment by hramezani** [comment]
Yes, as you mentioned there are two ways to fix it.

1. inheriting from BaseModel(which is the correct way)
2. set `env_prefix` to a random string then path would not be picked from env

**Comment by hramezani** [comment]
Closing as it is pydantic-settings default behavior and it's already documented
