### ISSUE TITLE
ValidationError when combining dotenv file, env_prefix and fields with alias

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic-settings#219]
I have the following settings setup:
- a non empty env prefix
- one or more fields with alias that starts with the env prefix.

MCVE:
```py
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="xxx__", env_file=".env")

    foo: str = ""
    bar_alias: str = Field("", alias="xxx__bar")


print(Settings().model_dump())
```

Populating the fields via env vars works:
```console
$ xxx__foo=1 xxx__bar=2 python testsettings.py
{'foo': '1', 'bar_alias': '2'}
```

Populating them via a dotenv file raises ValidationError:
```console
$ cat .env
xxx__foo=1
xxx__bar=2

$  python testsettings.py
Traceback (most recent call last):
...
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
bar
  Extra inputs are not permitted [type=extra_forbidden, input_value='2', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```

**Comment by hramezani** [comment]
Thanks @gsakkis for reporting this.

dotenv setting source consider `extra` config. So

> Pydantic settings consider extra config in case of dotenv file. It means if you set the extra=forbid (default) on model_config and your dotenv file contains an entry for a field that is not defined in settings model, it will raise ValidationError in settings construction.

This is not the case in env source because it will ignore the extra input.

You can ignore this behavior by adding `extra='ignore'` to your config

**Comment by gsakkis** [comment]
Thanks @hramezani for the quick reply! I'm not sure how the quoted docs are relevant here; `xxx__bar` does refer to a field defined in the model, it's not an `extra` I want to ignore.

**Comment by hramezani** [comment]
Sorry @gsakkis for misunderstanding. Now, I got your point.

I will prepare a patch to fix this bug

**Comment by hramezani** [comment]
I've created https://github.com/pydantic/pydantic-settings/pull/221 to fix it. it would be great to take a look or test it if you want

**Comment by samuelcolvin** [comment]
@gsakkis any chance you could review @hramezani's PR.

Otherwise, we'll merge and release next week.
