### ISSUE TITLE
Feature request: custom complex types

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic-settings#222]
Currently pydantic-settings determines whether a field is "complex" (nested) or not based on its annotation as follows:
```py
def _annotation_is_complex_inner(annotation: type[Any] | None) -> bool:
    if lenient_issubclass(annotation, (str, bytes)):
        return False

    return lenient_issubclass(annotation, (BaseModel, Mapping, Sequence, tuple, set, frozenset, deque)) or is_dataclass(
        annotation
    )
```

It would be convenient if one could register other settings-like types as complex (either per model or globally) so that nested env variable explosion works. Case in point, a [`GenerationConfig`](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig) from Hugging Face transformers.
 
Draft API:
```py
class TransfomerModelSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="model__", complex_annotations=(GenerationConfig,)
    )

    name_or_path: str
    generation_settings: GenerationConfig = GenerationConfig()
```
Then one could pass via env vars any of the dozens `GenerationConfig` fields:
```console
export model__name_or_path=foo 
export model__max_new_tokens=123
...
```

**Comment by hramezani** [comment]
It is possible to mark a field as complex(to be json decoded) by `ForceDecode` annotation


This added in https://github.com/pydantic/pydantic-settings/commit/3667aed73b8f52f33d4ef4ee87b8321c18fa81c2 and will be available in the next release.

Here is an example from doc:
```py
import os
from typing import List
from pydantic import field_validator
from typing_extensions import Annotated
from pydantic_settings import BaseSettings, ForceDecode, SettingsConfigDict
class Settings(BaseSettings):
    model_config = SettingsConfigDict(enable_decoding=False)
    numbers: Annotated[List[int], ForceDecode]
    numbers1: List[int]  # (1)!
    @field_validator('numbers1', mode='before')
    @classmethod
    def decode_numbers1(cls, v: str) -> List[int]:
        return [int(x) for x in v.split(',')]
os.environ['numbers'] = '["1","2","3"]'
os.environ['numbers1'] = '1,2,3'
print(Settings().model_dump())
#> {'numbers': [1, 2, 3], 'numbers1': [1, 2, 3]}
```
