### ISSUE TITLE
Reuse attributes inside settings class, and problem with overwriting them with env-vars

### ISSUE THREAD

**Issue by rappongy** [pydantic/pydantic-settings#227]
Hello!

I'm facing an error with defining my settings and changing them from env variables.

```
from pathlib import Path
from pydantic_settings import BaseSettings, FilePath

class Settings(BaseSettings):
     log_dir: Path = "logs"
     log_dir.mkdir(exist_ok=True)

     log_file: FilePath = log_dir / "info.log"

settings = Settings()
```

If I'm not changing default values like described, then all are working as expected:
- `logs` directory is created if if doens't exists.
- log file is created inside it.

But when I'm trying to change `log_dir` from env vars it changes. But the file doesn't change.
And if log directory doens't exists, the logging module will thrown an error.

So, I'm confused, that I cannot change setting variable and reuse it inside settings class again.
I can make log_file property/computed_field, but then I cannot change it within env var itself.

Does anybody can help, how to solve this scenario usage? Thank in advance.

**Comment by rappongy** [comment]
Maybe I can use root validators here, to reinitialze values that came from env vars... Somehow

**Comment by hramezani** [comment]
You can use [model_validator after mode](https://docs.pydantic.dev/latest/concepts/validators/#model-validators):

```py
from pathlib import Path
from typing import Any

from pydantic import model_validator
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    log_dir: str = "logs"
    log_file: str = "info.log"

    @model_validator(mode='after')
    def check_card_number_omitted(self) -> Any:
        log_dir = Path(self.log_dir)
        log_dir.mkdir(exist_ok=True)
        Path(log_dir / self.log_file).touch()
        return self

settings = Settings()
```
