### ISSUE TITLE
Passing an environment variable that should be parsed as `None`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [pydantic/pydantic-settings#228]
I have a settings variable that is `Optional`, like the following:

```python
from typing import Literal
from pydantic_settings import BaseSettings, SettingsConfigDict

class MySettings(BaseSettings):

    FOO: Optional[Literal["bar"]] = Field("bar", description="test")
```

Is there a mechanism where the user can pass the equivalent of a Python `None` as an environment variable? I read the section on ["Passing environment variable values"](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values), but it doesn't have an example for `None`.

Passing an environment variable like `export FOO=` will yield an error because the `input_value=''` and `input_type=str` (which is good --- we shouldn't change that!). So, I'm trying to figure out what the ideal mechanism is to pass a `None`. Is there some setting where I can define what a `None` value would be?

**Comment by hramezani** [comment]
I think it is related to https://github.com/pydantic/pydantic-settings/issues/199. we already have a [fix](https://github.com/pydantic/pydantic-settings/pull/206) for it but it has not been deployed yet.

It will be available in the next release.

**Comment by Andrew-S-Rosen** [comment]
Fantastic! That is just what I was looking for!
