### ISSUE TITLE
Give users the ability to override environment variables using SettingsConfigDict

### ISSUE THREAD

**Issue by kassett** [pydantic/pydantic-settings#231]
I have several Python applications that run in a single cluster in a single namespace using EKS. I would like to be able to set the environment variable ENVIRONMENT and have it passed to all BaseSettings objects in the namespace. However, I would like the ability to be able to override the variable with a prefix. I propose adding the argument ``prefix_optional``, which would search first for the env var with the prefix, and then fallback to the env var without. 

I have created a PR ( https://github.com/pydantic/pydantic-settings/pull/229 ) implementing this logic, but definitely open to suggestions about the API.

**Comment by kassett** [comment]
@PrettyWood Opened an issue in relation to my PR
https://github.com/pydantic/pydantic-settings/pull/229

**Comment by kassett** [comment]
If the idea is that you would need to do something along the lines of 
```from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings


class Setting(BaseSettings):
    foo: str = Field(validation_alias=AliasChoices('SPECIFIC_ENVIRONMENT', 'ENVIRONMENT'))


print(Setting())
````
I think that is perhaps a little more clunky. If env_prefix could be passed as a list however, that might be acceptable as well.
```        
class Setting(BaseSetting):
      model_config = SettingsConfigDict(env_prefix=['SPECIFIC_', ''])
```
@PrettyWood This is similar to the pattern you suggested. What do you think?

**Comment by PrettyWood** [comment]
I'd rather stick with `AliasChoices`.
If your concern is that you will have to repeat your prefix in all your aliases

```py
class Setting(BaseSettings):
    foo: str = Field(validation_alias=AliasChoices('prefix_foo', 'foo'))
    bar: str = Field(validation_alias=AliasChoices('prefix_bar', 'bar'))
    buz: str = Field(validation_alias=AliasChoices('prefix_bar', 'buz'))
```

you can just factorize

def gen_aliases(var_name: str) -> AliasChoices:
    return AliasChoices(f'prefix_{var_name}', var_name)

class Setting(BaseSettings):
    foo: str = Field(validation_alias=gen_aliases('foo'))
    bar: str = Field(validation_alias=gen_aliases('bar'))
    buz: str = Field(validation_alias=gen_aliases('buz'))
```

**Comment by kassett** [comment]
Obviously your word is final, but I do feel that this way is far less elegant, and that the use case described above is very common. May I ask what the advantage of AliasChoices, besides that it already exists? If the reasoning is that "we shouldn't implement this functionality because a way to accomplish the end goal already exists," I would say that allowing users to accomplish the same goal in multiple different ways is not something to be scoffed at.

**Comment by kassett** [comment]
@PrettyWood Is there any update on this? I totally get where you're coming from, but I do this is a reasonable use case with an elegant solution, and still don't totally understand why you prefer AliasChoises

**Comment by PrettyWood** [comment]
I'm not very active on pydantic-settings so my opinion doesn't matter more than others. But I know what it is to have plenty of options for more or less the same job and it's a pain in the a** for both maintainers and users.

**Comment by kassett** [comment]
For sure totally understand. Do you have an idea of who would be better to ask? @hramezani Do you have any ideas? I do feel like this is worth adding, and the work is already done?

**Comment by hramezani** [comment]
As we already have `AliasChoices` and we can use it for this purpose, I would use the `AliasChoices` and don't add a new config.

You also can have your custom `EnvSettingsSource` and override ``EnvSettingsSource.get_field_value`.
