### ISSUE TITLE
Desynchronization of the extra field documentation between ConfigDict and default creation of model_config

### ISSUE THREAD

**Issue by utkini** [pydantic/pydantic-settings#264]
Hello!

I think I found a small mistake in method documentation:

`pydantic` [says](https://github.com/pydantic/pydantic/blob/main/pydantic/config.py#L52) that the `extra` parameter will be `ignore` by default, but

`pydantic_settings` [sets](https://github.com/pydantic/pydantic-settings/blob/main/pydantic_settings/main.py#L222) this extra parameter to `forbid` by default

**Comment by sydney-runkle** [comment]
@utkini, thanks for reporting this!

@hramezani, could you take a look at this discrepancy? Thanks!

**Comment by hramezani** [comment]
It is not a mistake. it is a design decision to raise `ValidationError` in case of extra values

**Comment by utkini** [comment]
Got it, 
I rather wanted to suggest, maybe change the description of this parameter to `forbid` [here](https://github.com/pydantic/pydantic/blob/main/pydantic/config.py#L52)?

**Comment by hramezani** [comment]
This is for `pydantic-settings` and `pydantic` has different extra default.
So, no need to change the description on pydantic.
