### ISSUE TITLE
How can I use Settings().model_dump() to access property names directly instead of using a dictionary?

### ISSUE THREAD

**Issue by skhaz** [pydantic/pydantic-settings#267]
I have the following code

```python
from pydantic import AliasChoices
from pydantic import Field
from pydantic import RedisDsn
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    redis_dsn: RedisDsn = Field("redis://localhost:6379")

    def model_dump(self):
        return self

print(Settings().model_dump().redis_dsn)
```

And I would like to know how to access it using .redis_dsn instead of ['redis_dsn']. Is this possible?

Thank you.

**Comment by hramezani** [comment]
You can use
```py
settings = Settings()
print(settings. redis_dsn)
```

**Comment by skhaz** [comment]
It worked, but Pyright complains that there are missing parameters in the constructor. Is there a workaround besides ignoring the error with a comment?

<img width="590" alt="Screenshot 2024-04-11 at 11 10 51" src="https://github.com/pydantic/pydantic-settings/assets/46259/f50bad04-55cc-4ede-989d-6f70639cc429">

**Comment by hramezani** [comment]
hmmm, I am not sure.
Do you have same problem with mypy?

**Comment by skhaz** [comment]
Yes.

```
$ mypy settings.py
settings.py:17: error: Missing named argument "redis_dsn" for "Settings"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by hramezani** [comment]
Have you configured the [mypy](https://docs.pydantic.dev/latest/integrations/mypy/) plugin?

**Comment by skhaz** [comment]
I have added this to my pyproject.toml file.

```toml
[mypy]
plugins = pydantic.mypy
```

Do I need to install any additional packages? The page doesn't mention that.

**Comment by hramezani** [comment]
Here is the config that works for me. please try it:
```
[mypy]
plugins = pydantic.mypy

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True

[mypy-pydantic_core.*]
follow_imports = skip
```

**Comment by skhaz** [comment]
I tried the config, same problem.

**Comment by hramezani** [comment]
what version of mypy are you using?

**Comment by skhaz** [comment]
```shell
$ mypy --version
mypy 1.9.0 (compiled: yes)
```

Installed using `uv`

```shell
$ uv pip install mypy
```

**Comment by hramezani** [comment]
I don't have this problem with `mypy 1.9.0` but let's keep the issue open for a while to see if someone else complain

**Comment by skhaz** [comment]
If you want to reproduce:

```python
from pydantic import Field
from pydantic import RedisDsn
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict
from typing import Optional

class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    redis_dsn: RedisDsn = Field("redis://localhost:6379")


settings = Settings()

print(settings.redis_dsn)
```

My PyRight (on Zed) also complains

<img width="620" alt="Screenshot 2024-04-15 at 13 54 50" src="https://github.com/pydantic/pydantic-settings/assets/46259/1bcac00c-f828-40b2-950e-77357076471e">

**Comment by hramezani** [comment]
I tried the your example code with `mypy 1.9.0`. Unfortunately I couldn't reproduce it:

```bash
$ mypy --version 
mypy 1.9.0 (compiled: yes)
$ mypy /tmp/test8.py --config-file /tmp/mypy.ini
Success: no issues found in 1 source file
```
You probably need to clear you mypy cache: `rm -r .mypy_cache`

**Comment by skhaz** [comment]
This is not only a mypy issue, PyRight have the same complains.

**Comment by zhangbc97** [comment]
add `default` kwargs for Field might solve this problem
Field(default="redis://localhost:6379")

**Comment by zhangbc97** [comment]
> And how would it be for the settings that I don't want a default? I want to make it mandatory.

`Field(...)`

**Comment by skhaz** [comment]
Thank you @zhangbc97.

For who needs, here is a working example below:

```python
from pydantic import Field
from pydantic import RedisDsn
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict
from typing import Optional

class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    redis_dsn: RedisDsn = Field(default="redis://localhost:6379")

    mail_password: str = Field(default=..., min_length=3)


settings = Settings()

print(settings.redis_dsn)
print(settings.mail_password)
```
