### ISSUE TITLE
How to override nested list of dictionaries

### ISSUE THREAD

**Issue by asabellico** [pydantic/pydantic-settings#268]
Hello, i would like to override a value using environment vars, inside a config file of this kind:

```
instances:
  - id: "es1"
    url: "http://base_url:9200"
```

```
class InstanceConfig(BaseModel):
    id: str
    url: AnyUrl

class AppConfig(BaseConfig):
    instances: List[InstanceConfig]

    model_config = SettingsConfigDict(yaml_file="config.yaml", env_prefix="myproj_", env_nested_delimiter="__")
```

If I set this env var:

```
MYPROJ_INSTANCES__0__URL: "http://override_url:9200"
```

it gives me this error:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for AppConfig
instances
  Input should be a valid list [type=list_type, input_value={'0': {'url': 'http://override_url:9200'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type
```

cannot find any reference about this in `pydantic-settings` documentation, so i wonder if this is supported or not

**Comment by hramezani** [comment]
yaml setting source is not enabled by default and you have to enable it like:

```py
from typing import List, Tuple, Type

from pydantic import BaseModel, AnyUrl

from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
    TomlConfigSettingsSource,
)

class InstanceConfig(BaseModel):
    id: str
    url: AnyUrl

class AppConfig(BaseSettings):
    instances: List[InstanceConfig]

    model_config = SettingsConfigDict(yaml_file="config.yaml", env_prefix="myproj_", env_nested_delimiter="__")


    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        return init_settings, env_settings, dotenv_settings, file_secret_settings, TomlConfigSettingsSource(settings_cls)
```

Take a look at [doc](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#other-settings-source) also helps

**Comment by asabellico** [comment]
you are right. i forgot to add the BaseConfig class from which i was inheriting that same thing (except I enabled yaml, env and secret sources). still i can't override a value in a dictionary in a list as described in the issue :(

**Comment by asabellico** [comment]
in fact i'm able to override a simple type config from env var but cannot do it correctly with data nested in a list using the __0__ syntax in var name

**Comment by hramezani** [comment]
you can't override the item in a list. you can set it by setting the env lik:
`MYPROJ_INSTANCES='[{"id":"1", "url":"http://override_url:9200"}]'

**Comment by asabellico** [comment]
ok i was hoping it was possible even if not mentioned in the docs. thank you for the sanity check!
