### ISSUE TITLE
Cannot load prefixed nested model from dotenv.

### ISSUE THREAD

**Issue by voodoo11** [pydantic/pydantic-settings#279]
How to reproduce:

Given .env:
```env
NESTED_FOO=foo
BAR=bar
```

```python
from pydantic_settings import BaseSettings, SettingsConfigDict


class NestedConfig(BaseSettings):
    foo: str = ""
    model_config = SettingsConfigDict(env_prefix="NESTED_")


class Config(BaseSettings):
    nested: NestedConfig = NestedConfig()
    bar: str = ""
    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore", case_sensitive=False
    )


print(Config())
```

results in:
```python
nested=NestedConfig(foo='') bar='bar'
```
Setting env variable by hand e.g. `NESTED_FOO=foo python test.py` works fine.

**Comment by voodoo11** [comment]
@hramezani Thanks, that make sense. Is it possible then to override model config for submodels somehow?

**Comment by hramezani** [comment]
`pydantic-settigns` only loads the config for the models you are initializing(`Config` in your example) and collect values for the model fields. so it only consider the parent model configs
