### ISSUE TITLE
Unable to override loading of .env with .env.testing

### ISSUE THREAD

**Issue by tedsecretsource** [pydantic/pydantic-settings#282]
Without going into too much detail, is there a reason why I am unable to load a specific environment file if a `.env` file exists in the project? In other words…

Given I am in my testing environment and both a `.env` and a `.env.testing` files exist with valid entries
When I load my settings using `settings = Settings(_env_file=".env.testing")`
Then `settings.app_env` = 'testing'

However, `settings.app_env` = 'production' (because that is what is in the `.env` file).

What in the world am I missing? What could I possibly be doing wrong?

FWIW the _actual_ use case is a bit more complex than this but this is the behavior that seems to be happening. Any pointers would be greatly appreciated 🙏 

Ted

**Comment by hramezani** [comment]
Thanks @tedsecretsource for reporting the issue.

from the [doc](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#dotenv-env-support):
`
If you need to load multiple dotenv files, you can pass multiple file paths as a tuple or list. The files will be loaded in order, with each file overriding the previous one.
`

Here is an example of passing multiple .env files:
```py
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        # `.env.prod` takes priority over `.env`
        env_file=('.env', '.env.prod')
    )
```

**Comment by hramezani** [comment]
with one file it should be ok. I didn't get the problem. if you include a file name in `_env_file`, `pydantic-settings` should only loads that file and use the values from the file.

If it doesn't work, probably you already have some variable on your system environment that overrides the value from the file.

BTW, please create an example code and let me know how to reproduce the problem.

**Comment by tedsecretsource** [comment]
> probably you already have some variable on your system environment that overrides the value from the file

The output of `env` does not show any of the values in the `.env.testing` file, only normal server-related keys and values.

> BTW, please create an example code and let me know how to reproduce the problem.

I really appreciate the offer. I was hoping to avoid this but I can't see any way around it :( I'll see what I can do. Thanks for the offer.

**Comment by tedsecretsource** [comment]
Problem solved!

We had this line in one of the included files (vestige of a prior version before using pydantic-settings):

```python
load_dotenv(find_dotenv())
```
Naturally, that was putting the .env variables into the actual environment and overwriting anything we were sending in .env.testing… Live and learn 🤷 

Thanks for your help and I certainly hope this helps someone else in the future!

**Comment by robinelvin** [comment]
I believe I have the problem described here and I don't have any other env setup. I have a list of env files I want to load but in tests I specifically only want to load one of them. However this appears to be ignored.

With these models:

```python
class DatabaseSettings(BaseModel):
    """Database Configuration Settings"""

    driver: str = "mysql+pymysql"
    host: str = "localhost"
    port: int = 3306
    user: str = "mysql"
    password: str = ""
    database: str = "my_db"

class Configuration(BaseSettings):
    """Configuration settings"""

    database: DatabaseSettings = DatabaseSettings()

    test_mode: Optional[bool] = Field(False, validation_alias="TEST_MODE")
    port: Optional[int] = Field(8008, validation_alias="PORT")
    reload: Optional[bool] = Field(False, validation_alias="RELOAD")
    auto_migrate: Optional[bool] = Field(False, validation_alias="AUTO_MIGRATE")

    model_config = SettingsConfigDict(env_file=(".env", ".env.test", ".env.dev"))
```
*.env*
```shell
DATABASE='{"password": "aaaaaaaaa"}'
```

*.env.test*
```shell
DATABASE='{"driver": "sqlite", "password": "test_pw"}'
TEST_MODE=1
```

*.env.dev*
```shell
DATABASE='{"driver": "postgresql+psycopg2", "port": 5432, "user": "postgres", "password": "bbbbbbbb", "database": "dev_db"}'
RELOAD=1
TEST_MODE=0
```

*Test*
```python
class TestConfig:
    "Relies on .env.test"

    def test_config_loads_env_file(self):
        config = Configuration(_env_file=".env.test")
        assert config.model_dump() is not None
        assert config.database.password == "test_pw"
```

*Test Output*
```shell
E       AssertionError: assert 'bbbbbbbb' == 'test_pw'
E         
E         - test_pw
E         + bbbbbbbb
```
