### ISSUE TITLE
Type error on BaseSettings config

### ISSUE THREAD

**Issue by pikeas** [pydantic/pydantic-settings#29]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.3
pydantic compiled: True
install path: <...>/.venv/lib/python3.9/site-packages/pydantic
python version: 3.9.1 (default, Dec 19 2020, 12:43:07)  [Clang 12.0.0 (clang-1200.0.32.21)]
platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

With the following code:

```py
from pydantic import BaseModel, BaseSettings

class FooModel(BaseModel):
    value: str

    class Config:
        title = 'foo'


class FooSettings(BaseSettings):
    value: str

    class Config:
        env_prefix = 'FOO_'


class FooSettingsFixed(BaseSettings):
    value: str

    class Config(BaseSettings.Config):
        env_prefix = 'FOO_'
```

Pylance complains about `FooSettings`:

<img width="590" alt="Screen Shot 2021-01-14 at 15 49 34" src="https://user-images.githubusercontent.com/686573/104678324-0135ef00-56a0-11eb-9aaa-883cd539d3f2.png">

It looks like there may be something missing in the definition for BaseSettings, since BaseModel config works without subclassing BaseModel.Config.

**Comment by hramezani** [comment]
This is fixed in `pydantic-settings` by using `SettingsConfigDict`
