### ISSUE TITLE
CliSettingSource fails to handle `AliasChoices` and `AliasPath`

### ISSUE THREAD

**Issue by kschwab** [pydantic/pydantic-settings#306]
From #303, `CliSettingsSource` does not handle `AliasChoices` correctly:

```python
import pytest

from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings


def test_settings():
    class Check(BaseSettings, cli_parse_args=[]):
        field: str = Field(
            "foo",
            alias=AliasChoices(
                "ALIAS_NAME"
            )
        )

    assert Check().field == 'foo'
    assert Check(ALIAS_NAME="bar").field == 'bar'
```

**Comment by kschwab** [comment]
@hramezani I'll try to get to this soon. However, at first glance, I don't think CLI will be able to handle `AliasChoice` if it has multiple aliases. We will likely be limited to a single alias on the CLI. I will give it some thought.

**Comment by hramezani** [comment]
Thanks @kschwab for the issue.
I am ok to limit it to single alias if it is not possible to handle. But we need to mention this limitation in the documentation .

**Comment by kschwab** [comment]
I was able to sort it out, we can support both `AliasChoices` and `AliasPath`.
