### ISSUE TITLE
Unable to have file secret take precedence even with env_prefix present.

### ISSUE THREAD

**Issue by Bendik-ml** [pydantic/pydantic-settings#333]
Hello!

I saw somewhat of a similar issue here https://github.com/pydantic/pydantic/pull/2190 but it was closed due to settings-management being moved to its own repository. And i could not find mentions elsewhere.

I am in the process of converting some of our Settings code to Pydantic v2, and ran into this issue - exemplified with a unit test:

```python
def test_mlflowsettings_loading_secrets__file(monkeypatch):
    """Test loading arbitrary secret token from secret file."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_dir_path = pathlib.Path(temp_dir)

        # Create the secret file with the specified name
        secret_file_path = temp_dir_path / "test_token"
        secret_file_path.write_text("my_token_from_file")

        monkeypatch.setenv("test_token", "my_token_from_env")  # Variable also exists as an environment variable

        class TestSettings(BaseSettings):
            test_token: SecretStr

            # Ensure that file_secret_settings take precedent over env_settings upon instantiation.
            @classmethod
            def settings_customise_sources(
                cls,
                settings_cls: Type[BaseSettings],
                init_settings: PydanticBaseSettingsSource,
                env_settings: PydanticBaseSettingsSource,
                dotenv_settings: PydanticBaseSettingsSource,
                file_secret_settings: PydanticBaseSettingsSource,
            ) -> Tuple[PydanticBaseSettingsSource, ...]:
                return (
                    init_settings,
                    file_secret_settings,
                    dotenv_settings,
                    env_settings,
                )

            model_config = SettingsConfigDict(secrets_dir=temp_dir_path)

        settings = TestSettings()
        assert settings.test_token.get_secret_value() == "my_token_from_file"

```

As soon as i add the prefix to `SettingsConfigDict` to support both file secrets and environment variables for setting a field- in times when i do want to dynamically either read from env or from a secret - the test breaks:

```python
def test_mlflowsettings_loading_secrets__file(monkeypatch):
    """Test loading arbitrary secret token from secret file."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_dir_path = pathlib.Path(temp_dir)

        # Create the secret file with the specified name
        secret_file_path = temp_dir_path / "test_token"
        secret_file_path.write_text("my_token_from_file")

        monkeypatch.setenv("pre_test_token", "my_token_from_env")  # Variable also exists as an environment variable

        class TestSettings(BaseSettings):
            test_token: SecretStr

            # Ensure that file_secret_settings take precedent over env_settings upon instantiation.
            @classmethod
            def settings_customise_sources(
                cls,
                settings_cls: Type[BaseSettings],
                init_settings: PydanticBaseSettingsSource,
                env_settings: PydanticBaseSettingsSource,
                dotenv_settings: PydanticBaseSettingsSource,
                file_secret_settings: PydanticBaseSettingsSource,
            ) -> Tuple[PydanticBaseSettingsSource, ...]:
                return (
                    init_settings,
                    file_secret_settings,
                    dotenv_settings,
                    env_settings,
                )

            model_config = SettingsConfigDict(secrets_dir=temp_dir_path, env_prefix="PRE_")

        settings = TestSettings()
        assert settings.test_token.get_secret_value() == "my_token_from_file"

>           assert settings.test_token.get_secret_value() == "my_token_from_file"
E           AssertionError: assert 'my_token_from_env' == 'my_token_from_file'
E             
E             - my_token_from_file
E             ?               ---
E             + my_token_from_env
E             ?                ++
```

I have been made aware that if i were to rename the secret file to the prefix set, it will work - but i feel like this sort of defeats the purpose, i was under the impression that a `settings_customise_sources` would take care of the ordering of how the variables were set. If i were to deploy the application that only made use of file-secrets - or working locally with just environment variables - i was hoping it would work.

Albeit in the docs it is written:

> Even when using a secrets directory, pydantic will still read environment variables from a dotenv file or the environment, a dotenv file and environment variables will always take priority over values loaded from the secrets directory.

I was under the impression that environment variables would only behave this way if they were above file_secret_settings in the tuple ordering.

Is there something i perhaps have failed to consider / misunderstood? It is not possible to combine the two?

**Comment by hramezani** [comment]
> I have been made aware that if i were to rename the secret file to the prefix set, it will work 

Yes, this is the current behavior and we can't change it right now. because it will introduce a breaking change.

> i was under the impression that a settings_customise_sources would take care of the ordering of how the variables were set. If i were to deploy the application that only made use of file-secrets - or working locally with just environment variables - i was hoping it would work.

you can customise the order or sources by `settings_customise_sources`. you need to change the order per env(local or prod) if you want.

You can have both secrets and env sources together. you can set the envs and create the file by prefix as you mentioned above.

Let me know what I missed to answer?

**Comment by Bendik-ml** [comment]
> > I have been made aware that if i were to rename the secret file to the prefix set, it will work
> 
> Yes, this is the current behavior and we can't change it right now. because it will introduce a breaking change.
> 
> > i was under the impression that a settings_customise_sources would take care of the ordering of how the variables were set. If i were to deploy the application that only made use of file-secrets - or working locally with just environment variables - i was hoping it would work.
> 
> you can customise the order or sources by `settings_customise_sources`. you need to change the order per env(local or prod) if you want.
> 
> You can have both secrets and env sources together. you can set the envs and create the file by prefix as you mentioned above.
> 
> Let me know what I missed to answer?

No misses, thanks for responding - i can see how this is quite a breaking change.

I did find a workaround, which is defining a secretSettings class on my own:

```python
class CustomFileSecretSource(PydanticBaseSettingsSource):
    def __init__(self, settings_cls: Type[BaseSettings]):
        super().__init__(settings_cls)
        self.secrets_dir = settings_cls.model_config.get("secrets_dir")

    def get_field_value(self, field: str, field_info: Any) -> Tuple[Any, str, bool]:
        """Attempt to retrieve secret from file, and return a Tuple of shape[value, target, is_complex]."""
        if self.secrets_dir:
            file_path = self.secrets_dir / field
            if file_path.is_file():
                return file_path.read_text().strip(), field, False
        return None, field, False

    def __call__(self) -> Dict[str, Any]:
        """Call and set field."""
        d: Dict[str, Any] = {}
        for field, field_info in self.settings_cls.model_fields.items():
            value, field_key, is_complex = self.get_field_value(field, field_info)
            if value is not None:
                d[field_key] = value
        return d
```
Which disregards the prefix, and the unit tests now work with both the `env_prefix` and `secrets_dir` present:

```python
def test_mlflowsettings_loading_secrets__file(monkeypatch):
    """Test loading arbitrary secret token from secret file."""
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_dir_path = pathlib.Path(temp_dir)

        # Create the secret file with the specified name
        secret_file_path = temp_dir_path / "test_token"
        secret_file_path.write_text("my_token_from_file")

        monkeypatch.setenv("pre_test_token", "my_token_from_env")  # Variable also exists as an environment variable

        class TestSettings(BaseSettings):
            test_token: SecretStr

            # Ensure that file_secret_settings take precedent over env_settings upon instantiation.
            @classmethod
            def settings_customise_sources(
                cls,
                settings_cls: Type[BaseSettings],
                init_settings: PydanticBaseSettingsSource,
                env_settings: PydanticBaseSettingsSource,
                dotenv_settings: PydanticBaseSettingsSource,
                file_secret_settings: PydanticBaseSettingsSource,
            ) -> Tuple[PydanticBaseSettingsSource, ...]:
                return (
                    init_settings,
                    CustomFileSecretSource(settings_cls),
                    env_settings,
                    dotenv_settings,
                )

            model_config = SettingsConfigDict(env_prefix="PRE_", case_sensitive=False, secrets_dir=temp_dir_path)

        settings = TestSettings()
        assert settings.test_token.get_secret_value() == "my_token_from_file"
```

By no means perfect, but should someone else pass by it might work for them too.
