### ISSUE TITLE
Question about the parameter inference for the constructor in the class inherited from BaseSettings

### ISSUE THREAD

**Issue by laipz8200** [pydantic/pydantic-settings#334]
Hi!

There are many parameters in `BaseSettings` such as `_env_file` and `_case_sensitive`, but these parameters are not fields of `BaseSettings`. According to the definition from the [Python documentation](https://docs.python.org/3/library/dataclasses.html#inheritance), the `__init__` method of my own Settings class will not include these parameters unless I write them myself.

As a result, when I inherit from `BaseSettings` and create my own `Settings` class, once I pass parameters like `_env_file` to the `Settings`, the type checker(both Pyright and Mypy) will complain.

![image](https://github.com/pydantic/pydantic-settings/assets/16485841/fd62ae2b-54f8-4ccb-af4d-6fdaa379f968)

Do you have any plans to fix it? Or should we include these parameters as fields in the `BaseSettings` class? (I have tried this approach, it solves the problem but doesn't look very elegant.)

**Comment by hramezani** [comment]
Hi,

> There are many parameters in BaseSettings such as _env_file and _case_sensitive, but these parameters are not fields of BaseSettings. According to the definition from the [Python documentation](https://docs.python.org/3/library/dataclasses.html#inheritance), the __init__ method of my own Settings class will not include these parameters unless I write them myself.

These are configuration params that you can pass when initializing your setting class. we have same params in `SettingsConfigDict` as well but these are the params that have more priority over `SettingsConfigDict` params.

> As a result, when I inherit from BaseSettings and create my own Settings class, once I pass parameters like _env_file to the Settings, the type checker(both Pyright and Mypy) will complain.

Yes, you will get the error with `pyright` but I think you don't get error in `mypy` if you [enable pydantic mypy plugin](https://docs.pydantic.dev/latest/integrations/mypy/#enabling-the-plugin)

**Comment by laipz8200** [comment]
@hramezani Thank you for your reply!
