### ISSUE TITLE
Recommendations for background updates

### ISSUE THREAD

**Issue by AndreuCodina** [pydantic/pydantic-settings#352]
Azure Key Vault and Azure App Configuration load the settings in the `BaseSettings` model when the backend starts, but I need to refresh them given a configured interval.

Is there any recommendation to implement a refreshing interval? My main concerns are the following:

- The setting sources aren't asynchronous, and I don't want to block the backend.

- FastAPI in production is launched with workers (e.g. `fastapi run --workers 16 src/main.py`), and I don't want to refresh it 16 times instead of just once. It costs money and it wastes resources.

**Comment by hramezani** [comment]
@AndreuCodina There is no refresh mechanism right now in `pydantic-settings` and all the code is `sync` there.

The assumption is other parts of code e.g. backend need configuration to be loaded before they start. like listen IP, port number. Actually, `pydantic-settings` is designed to only initialize settings models once.

So, I don't have any strong recommendations for your use case.

**Comment by AndreuCodina** [comment]
FYI, I need it for this reason: https://learn.microsoft.com/en-us/azure/azure-app-configuration/reload-key-vault-secrets-dotnet
