### ISSUE TITLE
Provide working example for using YAML configuration file (and for other configuration sources)

### ISSUE THREAD

**Issue by vlcinsky** [pydantic/pydantic-settings#366]
# Quick hack
In my code, I loaded a YAML file and instantiated the `Settings`:

```python
class Settings(BaseSettings)
    name: str
    surname: str

def load_settings(config_path: Path | str):
    with open(config_path, "rb") as f:
        config = yaml.safe_load(f)
    settings = Settings(**config)
    return settings
```
and then anywhere I need:
```python
from .settings import load_settings
settings = load_settings("path/to/config.yaml")
```
This works.

# Trying to use `YamlConfigSettingsSource`

As `pydantic_settings` provides directly a`YamlConfigSettingsSource`, I thought, it would be simpler and better to use it.

## Expected solution (did not work)

Based on examples for env variables, dot env and parsed CLI line, my expectation was as follows:

```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(yaml_file='config.yaml', yaml_file_encoding='utf-8')
    # config model itself
    name: str
    surname: str

# instantiate using default file location
settings = Settings()

# or using custom file location
settings = Settings(_yaml_file="dev.yaml")
```
Of course, this would assume:

```shell
$ pip install pydantic_settings[yaml]
```

The sample above simply does not work.

## Working solution
Following code works for me:
```python
from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
    YamlConfigSettingsSource,
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(yaml_file="config.yaml")

    name: str
    surname: str

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        return (
            YamlConfigSettingsSource(settings_cls),
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
        )


class ProdSettings(Settings):
    model_config = SettingsConfigDict(yaml_file="prod.yaml")


settings = Settings()
print("default", settings.model_dump())

prod_settings = ProdSettings()
print("prod", prod_settings.model_dump())
```

My expectation that I will copy-paste a short example and be up and running in 10 minutes was wrong. It took me few hours to get it working.

## Why the simple solution failed
There are at least two reasons:
- argument `_yaml_file` is not supported by `BasicSettings.__init__` (this is the case for more recently added settings sources)
- `BaseSettings` is automatically attempting to support only subset of settings sources:
  - supported sources: `InitSettingsSource`, `EnvSettingsSource`, `DotEnvSettingsSource`, `SecretsSettingsSource`, `CliSettingsSource`
  - remaining settings sources must be explicitly added using `settings_customise_sources` classmethod.

# Proposed solution

## Provide working example for each settings source
There are settings sources:
- `SecretsSettingsSource`
- `EnvSettingsSource`
- `DotEnvSettingsSource`
- `CliSettingsSource`
- `JsonConfigSettingsSource`
- `PyprojectTomlConfigSettingsSource`
- `TomlConfigSettingsSource`
- `YamlConfigSettingsSource`
- `AzureKeyVaultSettingsSource`

Few of these sources have good examples provided, but the ones at the end do not.

Examples should show:
- simple Settings model
- how to define default configuration source parameters
- how to get settings using default configuration
- how to get settings from with non-default configuration source parameters

Following existing examples it shall be explained, how things work, if there are multiple files supported, if missing files are reported or is silently ignored (sometime causing subsequent "missing" error).

Examples of non-default configuration source parameters would reveal cases, where the convention, that configuration source parameters are available with underscore prefix name for customized instantiation is not really available yet. This should be stated explicitly (omitting non-default example can cause long search for expected solution without success).

## Plan to implement unified non-default instantiation for all config sources
This would include "only" the configuration sources, which are part of pydantic_settings library otherwise there would be a risk of parameter name clashes.

As this issue focuses on documentation, this "implement..." part would be fulfilled by creating relevant issues.

**Comment by hramezani** [comment]
Thanks @vlcinsky for reporting this issue.

Yeah, pydantic-settings now support yaml file. we couldn't change the signature of `settings_customise_sources`(because of breaking change) that's why we have to override `settings_customise_sources` and initialize `TomlConfigSettingsSource` there. there is an [example on the doc](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#other-settings-source).
We can get rid of the overriding `settings_customise_sources` probably in the next major release.
