### ISSUE TITLE
[docs] Should point out that `BaseSettings` uses different defaults than `BaseModel`

### ISSUE THREAD

**Issue by remisphere** [pydantic/pydantic-settings#37]
Hello,
Everything is in the title.

The documentation for [model_config](https://pydantic-docs.helpmanual.io/usage/model_config/) displays the defaults used for the `BaseModel`'s `Config` inner class, but nothing is said about `BaseSettings`'s `Config`.
One could reasonably assume that the defaults would be the same, yet they are not as some are modified [here](https://github.com/samuelcolvin/pydantic/blob/6b53cabe036a907a117e3530719befef2c417ae1/pydantic/env_settings.py#L88-L95), like `extra` and `validate_all`.

So I think this should be mentioned somewhere in the settings management page.

**Comment by hramezani** [comment]
Hello, sorry for late response.

`Pydantic V2` is on alpha state and we are working on documentation as well.
Also, `pydantic-settings` is not part of `Pydantic` from `V2` on and will have it's own documentation.
