### ISSUE TITLE
Allow SettingsConfigDict.secrets_dir to accept multiple directories

### ISSUE THREAD

**Issue by ponekscb** [pydantic/pydantic-settings#371]
It would be better if SettingsConfigDict.secrets_dir accepts tuple and look for secret files in multiple directories.

The following code should work by looking for both "aws_access_key_id" and "aws_secret_access_key" in "dir1" first, and then "dir2", like how pydantic-settings handles multiple dotenv files.
```python
from pydantic_settings import BaseSettings, SettingsConfigDict


class AWSSettings(BaseSettings):
    model_config = SettingsConfigDict(
        secrets_dir=("dir1", "dir2")
    )

    aws_access_key_id: str
    aws_secret_access_key: str
```

The idea came from this feature (taken from the document):
```python
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        # `.env.prod` takes priority over `.env`
        env_file=('.env', '.env.prod')
    )
```

I know that it makes less sense to seperate the secret files in multiple directories, but for some deployment infrastructure (GCP Cloud Run in my case), mounting multiple secrets inside a same directory is not supported (https://issuetracker.google.com/issues/221496605)

**Comment by hramezani** [comment]
Thanks @ponekscb for this feature request. I think we can introduce a new config names `secrets_dirs` that accepts multiple directories and deprecate the `secrets_dir`

**Comment by makukha** [comment]
I had the same problem, and made a simple package [pydantic-file-secrets](https://github.com/makukha/pydantic-file-secrets) with a custom settings source fully compatible with `SecretsSettingsSource`. I decided to keep `secrets_dir` config option, but its type is checked for `str | Path | list[str | Path]`.

@hramezani do you think this can be merged into `pydantic-settings` if i create a PR? Also, could you please take a look at [pydantic-file-secrets](https://github.com/makukha/pydantic-file-secrets) features, I would be glad to merge any of them to `SecretsSettingsSource `.

**Comment by hramezani** [comment]
> I had the same problem, and made a simple package [pydantic-file-secrets](https://github.com/makukha/pydantic-file-secrets) with a custom settings source fully compatible with `SecretsSettingsSource`. I decided to keep `secrets_dir` config option, but its value is checked for `str | Path | list[str | Path]`.

Ok, let's keep the `secrets_dir` and handle `list[str | Path]` as well.

> @hramezani do you think this can be merged into `pydantic-settings` if i create a PR? Also, could you please take a look at [pydantic-file-secrets](https://github.com/makukha/pydantic-file-secrets) features, I would be glad to merge any of them to `SecretsSettingsSource`.

Sure, it would be great to create a PR related to this issue and handle multiple directories for `secret_dir`.

For the other features of `pydantic-file-secrets` let's create issue for each feature one by one and if we accept the feature, you can create the PR and add the feature to `pydantic-settings`.

Please don't forget to add the test and updated the documents and examples if you want to create a PR.

Thanks!

**Comment by makukha** [comment]
> The following code should work by looking for both "aws_access_key_id" and "aws_secret_access_key" in "dir1" first, and then "dir2", like how pydantic-settings handles multiple dotenv files.

@ponekscb Please note that the `env_files` behaviour is that "dir2" takes priority over "dir1", that is, `secrets_dir` list will be searched in reverse direction, bottom to top.

**Comment by ponekscb** [comment]
@makukha Yeah, my mistake, I meant exactly like you said.


Anyway, thanks both of you a lot for the request

**Comment by hramezani** [comment]
added in https://github.com/pydantic/pydantic-settings/commit/12d85cf521bf2b07939241bf33f17d14d906623f
