### ISSUE TITLE
Take env variables as the highest priority by default

### ISSUE THREAD

**Issue by romanzdk** [pydantic/pydantic-settings#373]
I do not really understand the logic behind the default behaviour of priority between selecting settings attribute values. It feels counterintuitive to me that environment variables do not ALWAYS override ANYTHING that is in the code. Would it be possible to make the environment BY DEFAULT the highest priority? It is supper annoying to have to define the custom priority everytime I use settings (basically in every app amongst hundreds of them). I believe environment should always have highest priority as that's what it exist for - so I can override default behaviour of the app - either locally via e.g. .env file or in production using kubernetes configmap.

**Comment by makukha** [comment]
`EnvSettingsSource` is the second highest priority source by default. The first one, `InitSettingsSource`, I never used outside testing context (it is used when passing values to class constructor like `Settings(key='value')`). What is your use case that makes you use constructor values?

**Comment by hramezani** [comment]
You can create a custom base settings class and change the default priority there and then use it instead of `BaseSettings`

**Comment by romanzdk** [comment]
So I have multiple profiles for the app - dev, test, production. For the development purposes I set most of the variables in the constructor so the developer does not have to set up all the env vars. However, developer still should have an ability to easily override these settings via env var. That is the first case. Second case is integration tests. Again, some of the attributes are passed in constructor and some of them via env var as integration test in CI runs slightly differently than locally (e.g. different service hosts).

**Comment by makukha** [comment]
> So I have multiple profiles for the app - dev, test, production. For the development purposes I set most of the variables in the constructor so the developer does not have to set up all the env vars. However, developer still should have an ability to easily override these settings via env var.

For dev environment, I use reasonable default values for members of `class Settings(BaseSettings): ...`, and then env vars set in `compose.yml`. For apps packaged as Helm charts, I use a separate config file  (e.g. `app.toml`) for prod and env vars for dev and stage, keeping `class Settings` defaults as close to dev as possible.

> Second case is integration tests. Again, some of the attributes are passed in constructor and some of them via env var as integration test in CI runs slightly differently than locally (e.g. different service hosts).

For testing, can you pass ***all*** settings as env vars instead of constructor args?
