### ISSUE TITLE
Settings fail to load if different sources use different aliases

### ISSUE THREAD

**Issue by nejcskofic** [pydantic/pydantic-settings#378]
Contrived example is below:

```
import os

from pydantic import Field, AliasChoices
from pydantic_settings import BaseSettings


class MySettings(BaseSettings):
    original_name: str = Field(validation_alias=AliasChoices("DIFFERENT-NAME", "another"))


def test():
    os.environ["DIFFERENT-NAME"] = "abc"

    try:
        settings = MySettings(another="ghi")
    except Exception as e:
        print(e)
    else:
        print(settings)


if __name__ == '__main__':
    test()
```

This fails with error:
```
1 validation error for MySettings
another
  Extra inputs are not permitted [type=extra_forbidden, input_value='ghi', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```

It would succeed if there is no environment variable (resulting in `original_name=ghi`) or no constructor value (resulting in `original_name=abc`). Issue is that sources while ordered by priority do not take into account that aliases for each source may be different, resulting in multiple values which map to the same field. Pydantic correctly rejects this. Loading values from sources should take into account that there can be only one value per field.

Realistic scenario is when you are loading settings from environment variables and from remote configuration source (such as AWS Parameter Store) and naming convention is different for those (underscore vs dashes for variable naming).

**Comment by hramezani** [comment]
Thanks @nejcskofic for reporting this issue.

It is the behavior of `pydantic` and not related to `pydantic-settings`. So the following model in pydantic fails:

```py
from pydantic import BaseModel, ConfigDict
class MySettings(BaseModel):
    original_name: str = Field(validation_alias=AliasChoices("DIFFERENT-NAME", "another"))

    model_config = ConfigDict(extra='forbid')

MySettings(**{'DIFFERENT-NAME': 'abc', 'another': 'ghi'})
```

You can fix it by changing the extra config to `ignore`:

```py
import os

from pydantic import Field, AliasChoices
from pydantic_settings import BaseSettings, SettingsConfigDict


class MySettings(BaseSettings):
    original_name: str = Field(validation_alias=AliasChoices("DIFFERENT-NAME", "another"))

    model_config = SettingsConfigDict(extra='ignore')

def test():
    os.environ["DIFFERENT-NAME"] = "abc"

    try:
        settings = MySettings(another="ghi")
    except Exception as e:
        print(e)
    else:
        print(settings)


if __name__ == '__main__':
    test()

```

**Comment by nejcskofic** [comment]
Thank you, @hramezani, for your answer. While your proposed solution works, care must be taken that order of aliases is the same as order of sources (so if I have field named A in shell and AA in file config and shell takes precedence, then I need to have alias A, AA and not the other way around, since first occurrence will be taken and remaining will be dropped). This is clunky and was not necessary in v1 where this worked out of the box.

Ideally alias would be bound to source (so A is only searched for when loading environment variables and AA only when reading from file). Logic which merges values would be aware that those refer to the same field, so only single value per field would be passed to `pydantic` and `extra='ignore'` would be unnecessary.

**Comment by hramezani** [comment]
@nejcskofic, I'm not sure we want to bind aliases to sources. Right now `pydantic-settings` collects all the values from different sources with/without aliases and passes all of them to `pydantic`. if we want to merge values and keep the one that has priority, we need to know which values are from which sources when merging but we don't have this information at that point.

As this would be a breaking change, we can control this behavior (merging values based on priority) by a config flag.

I label this issue as a feature request.

**Comment by nejcskofic** [comment]
@hramezani I understand that this is not how library is designed and that changing its behavior would be a breaking change. I would add though that merging based on source priority already happens if there is only single alias or no alias (the highest priority wins).

As I require this behavior, I went with a different solution.
