### ISSUE TITLE
is there a nightly release on pypi for this project?

### ISSUE THREAD

**Issue by braindevices** [pydantic/pydantic-settings#382]
there are many new features I would like to use on current main branch, I wonder is there a nightly release or release candidate for this project? Or I have to install via pip git+https://github.com/pydantic/pydantic-settings.git

**Comment by hramezani** [comment]
@braindevices you have to install it from the repository's main branch. we will release a new version with all the new feature probably next week

**Comment by makukha** [comment]
> @braindevices you have to install it from the repository's main branch. we will release a new version with all the new feature probably next week

This sounds awesome! Missing `DefaultSettingsSource`.

**Comment by hramezani** [comment]
`pydantic-settings 2.5.0` has been released!
https://pypi.org/project/pydantic-settings/
