### ISSUE TITLE
Mypy reports error when passing a list to YamlConfigSettingsSource through yaml_file 

### ISSUE THREAD

**Issue by just-maiyak** [pydantic/pydantic-settings#401]
**pydantic version:** 2.8.2
**pydantic-settings version:** 2.5.2
**OS:** elementary

When I try to use multiple settings sources, I get the following typechecking error : 
```
error: Argument "yaml_file" to "YamlConfigSettingsSource" has incompatible type "list[str]"; expected "Path | str | list[Path | str] | tuple[Path | str, ...] | None"  [arg-type]
```
This is because `list` is invariant so `list[str]` cannot be narrowed to `list[Path | str]` (as per [this issue](https://github.com/python/mypy/issues/3351)).
I'll post a PR to replace `list[Path | str] | tuple[Path | str]`, but if we specifically need to check for `list | tuple`, we might distribute list and tuple over the unions.

**Comment by hramezani** [comment]
Closing the issue based on discussion on PR
