### ISSUE TITLE
add an option to not validate a model if all configuration options it contains are empty

### ISSUE THREAD

**Issue by MarcBresson** [pydantic/pydantic-settings#409]
Hello,

I have multiple BaseSettings models split into different categories (e.g. DatabaseConnectionInfo). They all source environment variables. 

To avoid running the validation too many times (and creating an overhead), and because [BaseModel Singleton](https://github.com/pydantic/pydantic/issues/586#issuecomment-2320692033) seems out of the question for now, I store one class instance at the bottom of my module where all the config are. See the example:

```python
class A(BaseSettings):
    one: int
    two: int

class B(BaseSettings):
    foo: str

a_config = A()
b_config = B()
```

However, some of them are not always needed, and because their evaluation now happens at module import, I run into issue where I have validation failure while I don't even need that config.

It would be cool to add an option that skip validation if none of the attribute have a corresponding env variable.

For example, if neither "ONE" and "TWO" are defined, then

```python
class A(BaseSettings):
    model_config = SettingsConfigDict(skip_validation_if_empty=True)

    one: int
    two: int
```

would give an empty model and trying to access one of its attribute would raise an error

```python
A().one
#> KeyError  attribute does not exist
```

My workaround for now is the following:

```python
import functools

from pydantic import BaseModel, ConfigDict, model_validator
from pydantic_settings import BaseSettings


class Empty(BaseModel):
    """
    represents an empty dictionnary (and only that).
    """

    model_config = ConfigDict(extra="forbid")


class BaseSettingsEmpty(BaseSettings):
    """
    If attributes defined in a BaseSettings are all empty in the environment,
    then an empty model is returned to make the decorated class optional.
    If at least one attribute has a corresponding environment variable then
    regular pydantic validation is run.
    It avoids putting None values as default for every attributes in the
    config class.
    """
    def __init__(self, *args, **kwargs):
        try:
            super().__init__(*args, **kwargs)
        except NameError as err:
            if str(err) == "Empty environment":
                # we replace the instance by a not validated model
                # Default values will still be available.
                self.__dict__.update(type(self).model_construct().__dict__)
            else:
                raise err

    @model_validator(mode="before")
    @classmethod
    def if_all_empty_ok(cls, data):
        if data == {}:
            raise NameError("Empty environment")
        return data


class A(BaseSettingsEmpty):
    one: int = 1
    two: int
```

```python
A()
#> A(one=1)

import os
os.environ["ONE"] = "2"
A()
#> ValidationError: 1 validation error for A
#> two
#>   Field required [type=missing, input_value={'one': '2'}, input_type=dict]
#>     For further information visit https://errors.pydantic.dev/2.6/v/missing
```

**Comment by hramezani** [comment]
Thanks @MarcBresson for this feature request.

can't you use the default value of `None` for your model fields?

This config flag does not make sense and is an exceptional case. as you are implementing your own `BaseSettings` class and there is an issue to re-evaluate the singleton, I am going not to accept this feature request.

Thanks!

**Comment by MarcBresson** [comment]
My workaround is not super clean (it is never a good idea to touch internal object dictionary). However I understand that it may be an edge case.

for reference only: all or nothing strategy
