### ISSUE TITLE
reconsider adding Singleton option for BaseSettings

### ISSUE THREAD

**Issue by MarcBresson** [pydantic/pydantic-settings#410]
It seems there is still interest for that feature : https://github.com/pydantic/pydantic/issues/586#issuecomment-2320692033

**Comment by hramezani** [comment]
Thanks @MarcBresson for bringing this issue up again. I will discuss this with the team and get back to you.

**Comment by hramezani** [comment]
@MarcBresson I discussed this with the team and we decided not to accept this feature request.

As we discussed in the previous issue you can handle the singleton creation in your code.

Thanks for bringing up this issue again and for your understanding!

**Comment by MarcBresson** [comment]
Thank you for reaching back.

Could you explain why you are not accepting it? Also, the discussion in the previous issue did not lead to any viable workaround.

**Comment by hramezani** [comment]
@MarcBresson 
I think it is not `pydantic-settings` responsibility to care about singleton instance. There are multiple workaround for this problem and you can implement one of them based on your requirements.

Also, adding a new config flag makes our configs more complex(which I think is complex right now) and needs maintenance work as well.

**Comment by n3rada** [comment]
It would be great to have a recommended workaround from your team, @hramezani. Combining the Singleton pattern with Pydantic v2 is challenging, and a suitable solution is missing from the documentation and existing issues.

**Comment by MarcBresson** [comment]
I ended up writing proxy functions for each and everyone of my Pydantic model with a cache so that I can benefit from lazy evaluation.

```python
from functools import cache

from pydantic_settings import BaseSettings


MySuperDopeModel(BaseSettings):
    foo: int
    bar: str


@cache
get_my_super_dope_model():
    return MySuperDopeModel()
```
