### ISSUE TITLE
Feature: Make argument flag configurable

### ISSUE THREAD

**Issue by guarin** [pydantic/pydantic-settings#414]
Hi, would it be possible to make the argument flag (the `--` prefix before argument names) configurable? I saw that it is hardcoded here:
https://github.com/pydantic/pydantic-settings/blob/7e7ccdbc7b27d3f3d292d35a3b5033ef740fd6f7/pydantic_settings/sources.py#L1624

Our use case is that we are migrating some tools from omegaconf to pydantic and would like to use pydantic-settings to parse CLI arguments. My understanding is that pydantic-settings always adds a `--` prefix before argument names whereas omegaconf doesn't add this prefix. It would be great to have an option to disable the prefix in pydantic-settings to make the transition backwards compatible.

I also saw that `--` is used in another place but am not sure if this would be relevant for this feature:
https://github.com/pydantic/pydantic-settings/blob/7e7ccdbc7b27d3f3d292d35a3b5033ef740fd6f7/pydantic_settings/sources.py#L1506

**Comment by hramezani** [comment]
Thanks @guarin for requesting this feature.

I think `--` is very common as a prefix. I am not sure that making this configurable would be a good idea.

@kschwab what do you think?

**Comment by kschwab** [comment]
@hramezani I agree that `--` is most common. I think this is mostly a maintainer question on what CLI features to support. Since we are `argparse` based, it is not much trouble to add since `argparse` supports this with [prefix chars](https://docs.python.org/3/library/argparse.html#prefix-chars). I'll put up a draft PR for reference.

**Comment by guarin** [comment]
Thanks so much for the PR! I just tried it out and it seems that argparse doesn't support having no prefix chars `prefix_chars=""`, so parsing arguments like `arg=5` doesn't work (this is sadly how omegaconf expects arguments). I guess this is out of scope as it would require changes in argparse itself.

**Comment by mpkocher** [comment]
> It would be great to have an option to disable the prefix in pydantic-settings to make the transition backwards compatible.

What does "disable" the prefix mean? I believe the prefix has to be non-empty. Argparse will probably do some wonky things if you step off the garden path. 

```
In [1]: import argparse

In [2]: for x in ('+', 'a'):
   ...:     p = argparse.ArgumentParser(prefix_chars=x)
   ...:     p.add_argument('i')
   ...:     p.add_argument('aj')
   ...:     p.print_help()
   ...: 
usage: ipython [+h] i aj

positional arguments:
  i
  aj

options:
  +h, ++help  show this help message and exit
usage: ipython [ah] [aj J] i

positional arguments:
  i

options:
  ah, aahelp  show this help message and exit
  aj J
```

Empty char:

```
In [4]: argparse.ArgumentParser(prefix_chars="")
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 argparse.ArgumentParser(prefix_chars="")
-> 1805 default_prefix = '-' if '-' in prefix_chars else prefix_chars[0]
   1806 if self.add_help:
   1807     self.add_argument(
   1808         default_prefix+'h', default_prefix*2+'help',
   1809         action='help', default=SUPPRESS,
   1810         help=_('show this help message and exit'))

IndexError: string index out of range
```

**Comment by kschwab** [comment]
@guarin, yes, it's a limitation of `argparse`, as well as most CLI parsing libraries. It would be a larger effort to support in `CliSettingsSource`.

If your use case allows for it, you could always use [environment variables](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#parsing-environment-variable-values) to mimic a CLI. e.g., on Linux the below invocations are equivalent when using Pydantic Settings:
```bash
$ python3 my_app.py --arg=5 --other_arg=6
$ arg=5 other_arg=6 python3 my_app.py
```
On Windows, using env vars to mimic the CLI is uglier, and could really only be done in a similar manner using PowerShell.
