### ISSUE TITLE
Regression of case sensitive environment variable support

### ISSUE THREAD

**Issue by slingshotvfx** [pydantic/pydantic-settings#419]
As of `v2.5.0` case sensitive environment variables no longer function properly:

```python
import os

from pydantic import BaseModel
from pydantic_settings import BaseSettings, SettingsConfigDict

class NestedSettings(BaseModel):
    A: str
    b: int

class Settings(BaseSettings):
    not_nested: str
    NESTED: NestedSettings | None
    NestedTwo: NestedSettings | None

    model_config = SettingsConfigDict(
        case_sensitive=True,
        extra="forbid",
    )

os.environ["not_nested"] = "test"
os.environ["NESTED"] = '{"A": "10", "b": "10"}'
os.environ["NestedTwo"] = '{"a": "10", "b": "10"}'

print(Settings())
```

result:
```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
not_nested
  Field required [type=missing, input_value={'NESTED': {'a': '10', 'b': '10'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
NestedTwo
  Field required [type=missing, input_value={'NESTED': {'a': '10', 'b': '10'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

changing `case_sensitive` to `False` works as expected.

see: https://github.com/pydantic/pydantic-settings/issues/295

**Comment by slingshotvfx** [comment]
On Windows 11 in Python 3.12.1

I misspoke actually, this is a regression maybe all the way back to `v2.2.0`

**Comment by hramezani** [comment]
Thanks for your quick response @slingshotvfx .

my question is why do you enable the `case_sensitive` in your model. as you said you are using windows and this config doesn't have any effect on windows:

from the doc:
`
On Windows, Python's os module always treats environment variables as case-insensitive, so the case_sensitive config setting will have no effect - settings will always be updated ignoring case.
`

**Comment by slingshotvfx** [comment]
Our code is cross-platform and we utilize `case_sensitive` for our Linux deployments.  I admit having `case_sensitive=True` in windows code is misleading if it really does nothing, but ideally it would still work and not throw a validation error.

**Comment by hramezani** [comment]
One solution would be to set `case_sensitive=False` when `pydantic-settings` in on `Windows`.

But you can do it on your side as well. like 

```py
case_sensitive=False if sys.platform.startswith('win') else True,
```

**Comment by hramezani** [comment]
No worries, let's mark this one as duplicate and close.
