### ISSUE TITLE
Separate tests related to specific settings sources

### ISSUE THREAD

**Issue by makukha** [pydantic/pydantic-settings#427]
Pydantic Settings has excellent test coverage, but tests are collected in only 3 files, leading to e.g. ~5200 lines in test_settings.py. IMO, testing code could be more maintainable if every source has a separate file, if possible.

I could provide PR if this improvement sounds reasonable.

**Comment by hramezani** [comment]
Thanks @makukha for this issue.

It would be great if you can help here.
