### ISSUE TITLE
Add tests for DefaultSettingsSource

### ISSUE THREAD

**Issue by makukha** [pydantic/pydantic-settings#428]
`DefaultSettingsSource` has no tests (except `__repr__()`).

I could come up with PR on this.

**Comment by hramezani** [comment]
@makukha When we initialize the settings class it uses the `DefaultSettingsSource`. we have some tests for it like `test_init_kwargs_nested_model_default_partial_update`. Do you know  some special missed cases?

So, there are

**Comment by makukha** [comment]
> We have some tests for it like test_init_kwargs_nested_model_default_partial_update. Do you know some special missed cases?

Sorry, I overlooked this one. This issue should be closed.
