### ISSUE TITLE
Support for suppressing fields from the CLI --help message

### ISSUE THREAD

**Issue by Geo5** [pydantic/pydantic-settings#431]
In stdlib argparse you are able to set the help message to `argparse.SUPPRESS` to hide the entry from the generated `--help` output.

Would it be possible to support this in pydantic-settings as well?
It seems to work, if you add a 
```python
if help==SUPPRESS:
  pass
elif ...
```
here https://github.com/pydantic/pydantic-settings/blob/main/pydantic_settings/sources.py#L1885
and setting the field description to `argparse.SUPPRESS`

**Comment by hramezani** [comment]
@kschwab Please take a look when you have time.

**Comment by kschwab** [comment]
@Geo5, I presume just like `argparse` this should be applied on a per field setting? e.g.:

```python
class Settings(BaseSettings):
    field: CliSuppress[int] = Field(description='Hide this field from help')
```

This is not hard to add, I can put up a PR if the above looks reasonable. Obviously, "field" still gets parsed at the CLI and is only hidden from CLI --help text.

**Comment by Geo5** [comment]
Yes exactly, it is only hidden from CLI --help, but still gets parsed.
Do i understand the library correctly, that if this would be added via a type parameter (e.g. `CliSuppress`) it would not be possible to set this dynamically at runtime?
The use case is, that i sometime want to show/hide some options depending on the environment (windows/linux, installed somewhere or not, etc), which with arparse would be something like:
```python
parser.add_argument("--foo", help=argparse.SUPPRESS if platform=="linux" else "This is the foo argument")
```

**Comment by kschwab** [comment]
That's a great point. I added support for both in #436. e.g.:

```python
class Settings(BaseSettings, use_attribute_docstrings=True):
    field: CliSuppress[int]
    """Hide this field from help"""
    
    foo: int = Field(description=CLI_SUPPRESS if platform=="linux" else "This is the foo argument")
```

**Comment by Geo5** [comment]
Looks great, thank you!
