### ISSUE TITLE
Error validating Literal types from .env

### ISSUE THREAD

**Issue by slingshotvfx** [pydantic/pydantic-settings#435]
Validation fails for non-string Literal types when reading values from the environment:

```python
import os
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict

class LiteralFromEnv(BaseSettings):
    A: bool
    B: Literal[False]
    C: int
    D: Literal[1]

    model_config = SettingsConfigDict(env_file=".env")

os.environ["A"] = "False"
os.environ["B"] = "False"
os.environ["C"] = "1"
os.environ["D"] = "1"

print(LiteralFromEnv().model_dump())
```

```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for LiteralFromEnv
B
  Input should be False [type=literal_error, input_value='False', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
D
  Input should be 1 [type=literal_error, input_value='1', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
```

This also occurs when reading from a .env file.  Presumably this is because all environment variables are strings, but `int` or `bool` types (for example) work, so I'd expect `Literal[<int>]` to work as well.

Using `python 3.12`, `pydantic-settings 2.4.0`, on `windows 10`

**Comment by hramezani** [comment]
Thanks @slingshotvfx for reporting this issue.

This is not a `pydantic-settings` issue. this is related to pydantic.

Here is the collected value for initializing the model `{'A': 'False', 'B': 'False', 'C': '1', 'D': '1'}`.

So, if we change the above model to a pedantic model, we will get the same error.
```py
from typing import Literal

from pydantic import BaseModel

class LiteralFromEnv(BaseModel):
    A: bool
    B: Literal[False]
    C: int
    D: Literal[1]


print(LiteralFromEnv(**{'A': 'False', 'B': 'False', 'C': '1', 'D': '1'}).model_dump())
```

Let's close this issue here and you can ask your question in [pydantic](https://github.com/pydantic/pydantic) repository

**Comment by slingshotvfx** [comment]
Hey @hramezani 

Raised an issue [here](https://github.com/pydantic/pydantic/issues/10566) but looks like Pydantic doesn't plan to support this feature unfortunately.  Might be nice to at least mention in the documentation for `pydantic-settings` that non-string Literals can't be used in conjunction with environment variables.


Thanks!

**Comment by hramezani** [comment]
Thanks @slingshotvfx for updating.

> Might be nice to at least mention in the documentation for pydantic-settings that non-string Literals can't be used in conjunction with environment variables.

As it is a `pydantic` limitation, I prefer not to mention this in the documentation. because there are some other limitation that we don't mention them in the docs
