### ISSUE TITLE
ImportError: cannot import name 'CliApp' from 'pydantic_settings'

### ISSUE THREAD

**Issue by m3g4p0p** [pydantic/pydantic-settings#442]
Dear all, 

I was reading the latest documentation which refers to a `CliApp` which I can see in the source code here, but appears not to be present in the code installed with pip (Linux x86_64).

```bash
$ python --version
Python 3.12.5

$ pip freeze
annotated-types==0.7.0
pydantic==2.9.2
pydantic-settings==2.5.2
pydantic_core==2.23.4
python-dotenv==1.0.1
typing_extensions==4.12.2

$ python -c 'from pydantic_settings import CliApp'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'CliApp' from 'pydantic_settings' (...)
```

Am I missing something?

Best,
Sebastian

**Comment by ZequnZ** [comment]
Seems like this feature is added recently after last release, so it is not published and cannot be used at this point.

I am also looking forward to this. Just asking here any plans/timelines for the next release?

**Comment by hramezani** [comment]
Thanks @m3g4p0p for the issue and @ZequnZ for the answer.

Yes, it has not been released yet. I will release a new version probably this week!

**Comment by m3g4p0p** [comment]
Hi @hramezani, ah cool thanks for the update! :)
