### ISSUE TITLE
`pydantic-settings` deep-merges complex values from different sources

### ISSUE THREAD

**Issue by YaraslauZhylko** [pydantic/pydantic-settings#457]
`pydntic-settings` versions: `2.6.0`, `2.5.2`, probably earlier versions as well

---

I have a `.env` file with a complex value inside:
```dotenv
TEST={"a":1,"b":2}
```

And I have the code:
```python
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    test: dict[str, int]
    model_config = SettingsConfigDict(env_file=".env")
```

If I run this code as-is, I get the expected values:
```python
>>> s = Settings()
>>> s.test
{'a': 1, 'b': 2}
```

But then I try to overide the value via an environment variable:
```shell
$ TEST='{"b":22,"c":33}' python
```

What I expect to see is the dict from `.env` being overwritten by the dict in the envvars.
What I get is:
```python
>>> s = Settings()
>>> s.test
# expected value:
# {'b': 22, 'c': 33}
# actual value:
{'a': 1, 'b': 22, 'c': 33}
```

It is a merger of the values from `.env` and envvars.
I would have expected this if my `test` was defined as an embedded Pydantic model.
But it is actually a single separate value that I expect to be completely overidden by an environment variable.

Is that behaviour expected?
If so, how can I work around it to get the value overridden?

**Comment by hramezani** [comment]
Thanks @YaraslauZhylko for reporting this.

Yes, this is expected behavior from `pydantic-settings`. the dotenv source returns `{'test': {'a': 1, 'b': 2}}` and env source returns `{'test': {'b': 22, 'c': 33}}`. Then `pydantic-settings` uses a `deep_update` function to merge them and pass it to `pydantic` for validation. so the end dict would be `{'a': 1, 'b': 22, 'c': 33}`.

This behavior lets `pydantic-settings` collect required model values from different sources.

> If so, how can I work around it to get the value overridden?

I don't have any easy workaround on top of my head. but you can define some fields instead of dict. like `a: int`, `b: int` and try to use them if it is possible.

The other workaround would be defining two separate fields like `test_dotenv`, `test_env` and provide values for one of them like:

```py
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    test_env: dict[str, int]
    test_dotenv: dict[str, int]

    model_config = SettingsConfigDict(env_file=".env")
```

**Comment by YaraslauZhylko** [comment]
Thanks for the prompt response, @hramezani!

As I mentioned I would expect this behaviour from an embedded Pydantic model, but not from a single field that just happens to be a dict. :thinking: 
But at least I know that this is actually "as designed".

BTW, would be cool to have some config flag to control this behaviour in the future.

**Comment by hramezani** [comment]
This behavior help people to collect a sub model field value or a field with type dict from multiple sources. like:

```py
from pydantic_settings import BaseSettings, SettingsConfigDict


class NestedSettings(BaseSettings):
    foo: str
    bar: str

class Settings(BaseSettings):
    test: NestedSettings

    model_config = SettingsConfigDict(env_file=".env", env_nested_delimiter="__")
```

Then you can collect `NestedSettings` values from two sources. e.g. put `test__foo=test-foo` in `.env` file and run the code by `test__bar=test-bar python ...`

BTW, I am afraid having a flag for disabling this behaviour make the code complex and brings extra requests.

**Comment by YaraslauZhylko** [comment]
> This behavior help people to collect a sub model field value or a field with type dict from multiple sources.

I'm 100% with this behaviour for nested models.
When you explicitly specify the structure of a desting settings block using Pydantic model.

But here we have a single value. That is a plain dict, and not a nested Pydantic model.
And I would expect it to be completely overriddent by a higher priority source.

Let's take  a look at another example:

I want to specify a list of allowed IP addresses.
I'd create something like this:
```python
class Settings(BaseSettings):
    allowed_ips: list[str]

    model_config = SettingsConfigDict(env_file=".env")
```
II put this into the `.env` file:
```dotenv
ALLOWED_IPS=["1.1.1.1", "2.2.2.2"]
```
But then I want to override it with another list for the test environment.
So I set the environment variable to:
```shell
ALLOWED_IPS='["2.2.2.2", "3.3.3.3"]'
```
In that case, the list from `.env` will be completely overwritten by the value from environment variable, resulting in `["2.2.2.2", "3.3.3.3"]`. It will **not** be merged with the underlying `.env` values like this: `["1.1.1.1", "2.2.2.2", "3.3.3.3"]`.
And this is the expected behaviour.

But now, instead of a list I want a mapping that lists the allowed IPs with the corresponding rate limits (requests per second).
So I create something like this:
```python
class Settings(BaseSettings):
    allowed_ips_with_rate_limits: dict[str | int]

    model_config = SettingsConfigDict(env_file=".env")
```
II put this into the `.env` file:
```dotenv
ALLOWED_IPS_WITH_RATE_LIMITS={"1.1.1.1": 10, "2.2.2.2": 20}
```
And if I want to override it in test environment, I'd set the environment variable to:
```shell
ALLOWED_IPS_WITH_RATE_LIMITS='{"2.2.2.2": 50, "3.3.3.3": 60}'
```
And I would expect exactly the same behaviour: the envvar should take precidence and give me the overridden value of `{"2.2.2.2": 50, "3.3.3.3": 60}`, and not a merged value of `{"1.1.1.1": 10, "2.2.2.2": 50, "3.3.3.3": 60}`.

The fine line here is the Paydantic model (clearly defined dested structure that should be merged from different sources) vs. a **single** `dict` value (that is clearly a separate concrete value, and not a defined nested structure).

The current behaviour is especially akward when compared to the `list` behaviour described above.

So my suggestion is to differentiate between Pydantic models and plain dicts when determining the merging strategy.

**Comment by hramezani** [comment]
Thanks @YaraslauZhylko for explaining. There are a couple of concerns:

- Each source returns a mapping between the field name and its value. e.g. in your example, the mapping is like `{'allowed_ips_with_rate_limits': {...}}`. `pydantic-settings` does not have any info about the type of field when merging the values.
- This is the behavior that people's code depends on, and changing it will introduce a breaking change. However, if we find a solution, we can introduce a new flag to prevent people from breaking their code.

I am not sure how complex is the change. I am going to talk with the team and will update the issue by their feedback

**Comment by YaraslauZhylko** [comment]
Thanks @hramezani!

**Comment by hramezani** [comment]
@YaraslauZhylko here is the feedback:

We will not change the behavior because this lets users update nested fields easily. Also, as I mentioned above, implementing a flag to disable this behavior for dicts will be complex.
But, you can [customize the setting sources](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#customise-settings-sources) to ignore the values from dotenv source if the value is already available in env source. like:

```py
from typing import Any, Tuple, Type

from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource, DotEnvSettingsSource, SettingsConfigDict


class MyDotEnvSettingsSource(DotEnvSettingsSource):
    def prepare_field_value(self, field_name: str, field: FieldInfo, value: Any, value_is_complex: bool) -> Any:
        value = super().prepare_field_value(field_name, field, value, value_is_complex)
        if field_name == "test" and self.settings_sources_data['EnvSettingsSource'] is not None:
            return None
        return value

class Settings(BaseSettings):
    test: dict[str, int]

    model_config = SettingsConfigDict(env_file=".env")

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        return init_settings, env_settings, MyDotEnvSettingsSource(settings_cls), file_secret_settings


print(Settings())

```
