### ISSUE TITLE
Tests need to strip environment variables before running

### ISSUE THREAD

**Issue by CyberTailor** [pydantic/pydantic-settings#463]
The following tests fail when run by the Portage package manager:

```
tests/test_settings.py::test_ignore_empty_with_dotenv_when_empty_uses_default
tests/test_settings.py::test_ignore_empty_with_dotenv_when_not_empty_uses_value
```

They expect `${A}` to be unset, while this is [one of variables](https://devmanual.gentoo.org/ebuild-writing/variables/) defined by portage.

Relevant section in "Problems faced when downstream testing Python packages":
https://mgorny.pl/articles/downstream-testing-python-packages.html#home-directory-use-config-leakage

**Comment by CyberTailor** [comment]
Some tests also fail with `COLUMNS` value other than 80, e.g.:

```sh
$ COLUMNS=81 pytest -vv "tests/test_source_cli.py::test_cli_help_default_or_none_model"
```

**Comment by hramezani** [comment]
Thanks @CyberTailor for reporting.

Can you make a PR to change these tests?
