### ISSUE TITLE
env_prefix ignored if extra=allow

### ISSUE THREAD

**Issue by iAnanich** [pydantic/pydantic-settings#474]
Problem: if model has both `extra="allow"` and `env_prefix` set, then model will have *all* envvars regardless of prefix, essentially ignorring `env_prefix` config.

Expected behavior: fields that match `env_prefix` can be added into model, even if they are not declared.

Noticed that it changed when upgraded, remember that in 2.1 it was clsoer to that, but also actually didn't include undeclared vars from .env . But having undeclared vars in .env that is shared between multiple nested settings files broke my code :)

Example code:
```python
from pydantic_settings import BaseSettings

class MySettings(BaseSettings):
    class Config:
        env_prefix = "MY_PREFIX_"
        case_sensitive = False
        env_file = ".env"
        extra = "allow"
    not_in_a_file: str = "yes"
    inside_file: bool = False

obj = MySettings()
print(obj)

if not obj.inside_file:
    print(".env/MY_PREFIX_inside_file is not detected, even though it's declared.")
if "notaprefix" in obj.model_dump():
    print("undeclared var that doesn't match prefix got into object.")
if not "bar" in obj.model_dump():
    print("did not get undeclared but matching prefix envvar: .env/MY_PREFIX_BAR")
    if "my_prefix_bar" in obj.model_dump():
        print("\t... but it is there with it's prefix.")
```
respective `.env` to test:
```
NOTAPREFIX=True
MY_PREFIX_inside_file=True
MY_PREFIX_BAR=1
```

So latest main gives this output:
```
not_in_a_file='yes' inside_file=True notaprefix='True' my_prefix_bar='1'
undeclared var that doesn't match prefix got into object.
did not get undeclared but matching prefix envvar: .env/MY_PREFIX_BAR
	... but it is there with it's prefix.
```
and `v2.1.0` gives this:
```
not_in_a_file='yes' inside_file=True
did not get undeclared but matching prefix envvar: .env/MY_PREFIX_BAR
```

**Comment by hramezani** [comment]
Thanks @iAnanich for reporting this.

Yeah, it it an expected behavior and we already [documented it](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#nested-model-default-partial-updates): 

`
Pydantic settings loads all the values from dotenv file and passes it to the model, regardless of the model's env_prefix. So if you provide extra values in a dotenv file, whether they start with env_prefix or not, a ValidationError will be raised.
`

**Comment by hramezani** [comment]
The reason that we collect all the values in `.env` is, `pydantic` has to handle these flags. it means if you define a model with `extra='forbid'`, you expect to get a validation error if there is an extra value presented in the `.env` file. So, if we only collect the values start with `prefix`, we will ignore the other values and the model won't raise validation error.
