### ISSUE TITLE
Parsing Secret[] values error

### ISSUE THREAD

**Issue by zoola969** [pydantic/pydantic-settings#475]
When attempting to parse an environment variable to a Secret[], the pydantic-settings module raises an error.

How to reproduce:

```python
import os

from pydantic import PostgresDsn, SecretStr, Secret
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    DSN1: SecretStr
    DSN2: PostgresDsn
    DSN3: Secret[PostgresDsn]


os.environ["DSN1"] = "postgresql://user:password@localhost/db"
os.environ["DSN2"] = "postgresql://user:password@localhost/db"
os.environ["DSN3"] = "postgresql://user:password@localhost/db"

settings = Settings()
```

Expected behaviour:
DSN3 successfully parsed into Secret[PostgresDsn] type

Actual behaviour: 
`pydantic_settings.sources.SettingsError: error parsing value for field "DSN3" from source "EnvSettingsSource"`

Additional info:
As I understood from the stacktrace, DSN3 is marked as a complex field, and pydantic-settings attempts to parse it from JSON.

**Comment by hramezani** [comment]
Thanks @zoola969 for reporting this issue.

I will investigate the problem and will prepare a fix.

**Comment by hramezani** [comment]
@zoola969 I created https://github.com/pydantic/pydantic-settings/pull/478 to fix the problem.

Could you please confirm?

**Comment by zoola969** [comment]
@hramezani checked on your branch, works good, thanks
