### ISSUE TITLE
Relax default `protected_namespaces` config setting (remove `model_`)

### ISSUE THREAD

**Issue by EliasRas** [pydantic/pydantic-settings#482]
Pydantic relaxed `protected_namespaces` default to get rid of warnings in e.g. AI/ML context (https://github.com/pydantic/pydantic/pull/10441). Would it be possible to make a similar change here?
https://github.com/pydantic/pydantic-settings/blob/6fe3bd1e35ff3854808f57e099484317f7063238/pydantic_settings/main.py#L427

**Comment by hramezani** [comment]
Thanks @EliasRas for reporting this.

Sure, we can do it here as well.

**Comment by hramezani** [comment]
I created https://github.com/pydantic/pydantic-settings/pull/483 as a fix

**Comment by ZidongLiu** [comment]
Thanks for taking immediate action, also encountered same issue here.

**Comment by hramezani** [comment]
The fix will be available in the next release
