### ISSUE TITLE
Question: what is a better approach to load from .env based on context?

### ISSUE THREAD

**Issue by roman-isakov** [pydantic/pydantic-settings#485]
Hello, 

I have multiple config files for browser, stored individually, i.e.:

```
./browser_config/config.chrome-qa.env
./browser_config/config.remote-chrome-qa.env
./browser_config/config.remove-firefox-dev.env
...
```

then I have **config.py**

```
from typing import Optional

from pydantic_settings import BaseSettings

from selenium_tests import browser_config_path


class Settings(BaseSettings):
    context: str = 'chrome-qa'

    driver_name: str = "chrome"
    base_url: str = "https://example.com"
    timeout: float = 15.0
    ...
    
    @classmethod
    def in_context(cls, env: Optional = None) -> 'Settings':
        asked_or_current = env or cls().context
        return cls(
            _env_file=browser_config_path / f"config.{asked_or_current}.env",
            context=asked_or_current,
        )

```

This sample code does its job, but I have a vague doubt that there must be another correct way to solve this problem.

I honestly ran through the documentation, but frankly I didn't find what I needed there, or I wasn't looking hard enough.

Can you please suggest how to load the .env file, based on the environment variable or depending on the context I passed through the function argument ?

Why do I keep the .env files separate? Because with pytest_generate_tests you can conveniently create tests for different configurations within a single test run.

Thanks in advance.

P.S.
Currently used libraries:
```
pydantic              2.10.2
pydantic_core         2.27.1
pydantic-settings     2.6.1
...
```

**Comment by hramezani** [comment]
@roman-isakov Thanks for this issue.

In general, it looks good. but probably you can move the `in_context` method out of your settings class like:

```py
import os

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    foo: str


def load_settings():
    return Settings(_env_file=os.getenv('CONTEXT', '.default.env'))
```

**Comment by roman-isakov** [comment]
@hramezani thank you for reply.

I'm confused with creating a settings object by passing value to _protected `_env_file`  argument, or is it expected behaviour?

Thanks in advance.

**Comment by hramezani** [comment]
This is expected and [documented](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#dotenv-env-support).

This is useful for the time when you don't know env file name when you define the model

**Comment by roman-isakov** [comment]
@hramezani 

Thank you so much for your time. That was quite a comprehensive comment, I have no questions left.

I will close this issue.
