### ISSUE TITLE
multiple inheritance: changed MRO

### ISSUE THREAD

**Issue by ergleb78** [pydantic/pydantic-settings#49]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Does it look like MRO is getting changed somehow when inheriting from BaseSettings? (I'm probably missing something)?

### Example Code

```Python
from pydantic import BaseSettings


class ConfigBase(BaseSettings):
    p1: str = None


class AppConfig(ConfigBase):
    p2: str = "AppConfig"


class AWSConfigBase(ConfigBase):
    p1: str = "AwsConfigBase"


class Config(AppConfig, AWSConfigBase):
    pass


print(Config().p1)

> None

where as without BaseSettings


class ConfigBase:
    p1: str = None


class AppConfig(ConfigBase):
    p2: str = "AppConfig"


class AWSConfigBase(ConfigBase):
    p1: str = "AwsConfigBase"


class Config(AppConfig, AWSConfigBase):
    pass


print(Config().p1)

> AwsConfigBase
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: ........./python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
                     platform: macOS-13.0.1-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
As @soamicharan mentioned it is by design in pydantic. you can get different values by changing the
```py
class Config(AppConfig, AWSConfigBase):
```
to 
```py
class Config(AWSConfigBase, AppConfig):
```
