### ISSUE TITLE
`BaseSettings.__init_subclass__()` takes no keyword arguments

### ISSUE THREAD

**Issue by JoshLoecker** [pydantic/pydantic-settings#494]
When creating a new BaseSettings class, I get an error that states the `__init_subclass__` function takes no keyword arguments. I've taken the following example directly from the [Pydantic Settings Docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#cli-kebab-case-for-arguments)

```python
import sys

from pydantic import Field

from pydantic_settings import BaseSettings


class Settings(BaseSettings, cli_parse_args=True, cli_kebab_case=True):
    my_option: str = Field(description='will show as kebab case on CLI')


try:
    sys.argv = ['example.py', '--help']
    Settings()
except SystemExit as e:
    print(e)
```

The output is as follows

```
Traceback (most recent call last):
  File "/Users/joshl/Library/Application Support/JetBrains/PyCharm2024.3/scratches/scratch_13.py", line 8, in <module>
    class Settings(BaseSettings, cli_parse_args=True, cli_kebab_case=True):
  File "/Users/joshl/Projects/COMO/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 137, in __new__
    cls = cast('type[BaseModel]', super().__new__(mcs, cls_name, bases, namespace, **kwargs))
  File "/Users/joshl/.local/share/uv/python/cpython-3.10.15-macos-aarch64-none/lib/python3.10/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Settings.__init_subclass__() takes no keyword arguments
```

```
> pip list

pydantic            2.10.3
pydantic-core       2.27.1
pydantic-settings   2.6.1
```

I'm seeing a few closed/fixed issues surrounding this, but I'm still having problems

[Pydantic #2522](https://github.com/pydantic/pydantic/issues/2522)
[Pydantic #6499](https://github.com/pydantic/pydantic/issues/6499)

(Not sure if these details are relevant, but I thought I would include them anyway)
Python: 3.10.15
Hardware: Macbook Pro M3
OS: MacOS 15.1.1

**Comment by JoshLoecker** [comment]
I'm able to fix this by installing directly from source, i.e., `pip install "git+https://github.com/pydantic/pydantic-settings"`

**Comment by hramezani** [comment]
Thanks fro the feedback. I close the issue and the fix will be available in the next release!
