### ISSUE TITLE
`env_file` Parameter Ignored  

### ISSUE THREAD

**Issue by Abdeldjalil-H** [pydantic/pydantic-settings#498]
**Description**:  
The `env_file` parameter does not behave as expected. Regardless of the value passed to `env_file`, the library always defaults to using `.env`. This makes it impossible to specify a custom `.env` file, as any provided value is ignored.  

**Steps to Reproduce**:  

1. Create two `.env` files:  
    - `.env` with content:  
      ```
      MY_VAR=from_dot_env
      ```  
    - `custom.env` with content:  
      ```
      MY_VAR=from_custom_env
      ```  

2. Use the following code:  
    ```python
    from pydantic_settings import BaseSettings, SettingsConfigDict

    class Settings(BaseSettings):
        my_var: str

        model_config = SettingsConfigDict(env_file="custom.env")

    settings = Settings()
    print(settings.my_var)  # Expected: "from_custom_env"
    ```

3. Run the code.  

**Expected Behavior**:  
The output should be `"from_custom_env"`, as the `env_file` parameter was explicitly set to `"custom.env"`.  

**Actual Behavior**:  
The output is `"from_dot_env"`, indicating that `.env` is always used, ignoring the value of `env_file`.  

**Environment**:  
- Pydantic version: `2.6.1` 
- Python version: `3.12`  
- OS: Ubuntu

**Comment by hramezani** [comment]
Thanks @Abdeldjalil-H for reporting this.

`pydantic-settings` respects the `env_file` and I couldn't reproduce the problem.

Probably you have `my_var` in your environment variables that overrides the value from `custom.env`

**Comment by Abdeldjalil-H** [comment]
Thank you for the clarification @hramezani . That was indeed the case. Closing the issue.
