### ISSUE TITLE
Have a way to force environment variable names to upper case regardless

### ISSUE THREAD

**Issue by hmpf** [pydantic/pydantic-settings#50]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In V1, given an OS that has case sensitive environment variable names: If you have a settings-object like the below (simplified from the pydantic docs):

```
class Settings(BaseSettings):
    foo: str
```

then: If only "FOO" is set, "FOO" is obviously used. Likewise if only "foo" is set, "foo" is used. But if both "foo" and "FOO" is set, "foo" is preferred. This is a bit surprising!

I'm used to environment variable names always being upper case, regardless. For that reason, I would like the ability to only read from upper case environment variable names regardless of what it looks like in the rest of the code. This could look like:

```
    class Config:
            force_uppercase_names = True  # Default: unset,  no change from current system
```

or

```
    class Config:
            environment_name_casing = "upper"  # Default: None/unset, no change from current system
```

At minimum, the docs should be updated with a warning that on an OS with case sensitive environment variable names and `case_sensitive` set to False, this will occur, to simplify tracking down the obscure bugs I can see this leading to.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
You can use `case_sensitive` config and set all your environment variables upper-case. Then you have to define your settigns fields upper-case as well. Here is an example in `pydantic-settings`:

```py
from pydantic import ConfigDict

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    FOO: str

    model_config = ConfigDict(case_sensitive=True)

import os
os.environ['FOO'] = 'test1'
os.environ['foo'] = 'test'

print(Settings())
# FOO='test1'
```

If you don't want to use upper-case field names, you can use `Field.validation_alias`:

```py
from pydantic import ConfigDict, Field

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    foo: str = Field(validation_alias='FOO')

    model_config = ConfigDict(case_sensitive=True)

import os
os.environ['FOO'] = 'test1'
os.environ['foo'] = 'test'

print(Settings())
# foo='test1'
```

Note: `pydantic-settings` is in alpha state. You can install it by `pip install pydantic-settings --pre`
