### ISSUE TITLE
Add `env_prefix` to `BaseSettings` args

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic-settings#74]
Currently `BaseSettings` can take the following config values from its `__init__` method:

https://github.com/pydantic/pydantic-settings/blob/c05410f4bd380fa2769bb9a674d32db0f2353d0f/pydantic_settings/main.py#L47-L54

Then these values are used if provided, else the ones from the `SettingsConfigDict`, e.g.:

https://github.com/pydantic/pydantic-settings/blob/c05410f4bd380fa2769bb9a674d32db0f2353d0f/pydantic_settings/main.py#L109-L114

Is there a reason why `env_prefix` isn't part of this scheme? If this is possible, I can make a PR implementing this.

**Comment by hramezani** [comment]
It's not only `env_prefix`. `case_sensitive` is not also included in `__init__`.

I think we can include both of them. PR welcome

**Comment by Viicos** [comment]
Nice, will do
