### ISSUE TITLE
SettingsConfigDict should have `total=False`

### ISSUE THREAD

**Issue by aradkdj** [pydantic/pydantic-settings#81]
Hi :wave: 

I just saw the [FastAPI 0.100.0 prerelease announcement](https://github.com/tiangolo/fastapi/releases/tag/0.100.0-beta1), the [Pydantic v2 migration guide](https://docs.pydantic.dev/dev-v2/migration/) and wanted to give this all a try with a little sample project.

```python
from pydantic import PostgresDsn
from pydantic_settings import BaseSettings
from pydantic_settings.main import SettingsConfigDict


class Settings(BaseSettings):
    ENVIRONMENT: str = "development"
    SQLALCHEMY_DATABASE_DSN: PostgresDsn = (
        # Specifying the psycopg dialect since it is different from the default
        # psycopg2, using 127.0.0.1 instead of localhost to disambiguate IPv4 vs IPv6
        "postgresql+psycopg://test:test@127.0.0.1/test"
    )

    model_config = SettingsConfigDict(case_sensitive=True, env_file=".env")
``` 

The line with `model_config = SettingsConfigDict(case_sensitive=True, env_file=".env")` is currently giving me the following warnings: "Parameter 'env_file_encoding' unfilled", "Parameter 'env_nested_delimiter' unfilled", "Parameter 'env_prefix' unfilled" and "Parameter 'secrets_dir' unfilled", which does not happen with this equivalent normal Pydantic model:

```python
from pydantic import BaseModel, ConfigDict


class SomeModel(BaseModel):
    id: int

    model_config = ConfigDict(from_attributes=True)
``` 

The only difference I found is that `pydantic.ConfigDict` is declared as `class ConfigDict(TypedDict, total=False)`, while `pydantic_settings.main.SettingsConfigDict` is lacking that optional parameter. Adding it seems to do the trick. I'm happy to open a PR with the change if you guys consider it is the right approach.

**Comment by hramezani** [comment]
Hi @aradkdj 

Thanks for reporting this issue.

Yes, you are right. It's already fixed in main and will be released on next beta

https://github.com/pydantic/pydantic-settings/blob/b08fa5bef3d02754adb15ebf0e69356051398f51/pydantic_settings/main.py#L22
