### ISSUE TITLE
Badly formatted code blocks garble up docs

### ISSUE THREAD

**Issue by fredrikaverpil** [pydantic/pydantic-settings#88]
![image](https://github.com/pydantic/pydantic-settings/assets/994357/810205e6-4076-4184-a3d0-9f927955c0cd)

This gets repeated whenever you have three backticks followed by `test="skip" lint="skip"`. I tried removing them in #87 but then all CI test checks [failed](https://github.com/pydantic/pydantic-settings/actions/runs/5374619268?pr=87). 😅

**Comment by fredrikaverpil** [comment]
It's possible that there's an issue with pytest-examples where it doesn't work well with the main pydantic docs including the markdown file from this repo.

**Comment by hramezani** [comment]
Thanks @fredrikaverpil for reporting this.

It got fixes in https://github.com/pydantic/pydantic-settings/commit/584a57b1c0b9833b130af59f4801ed5c093e04b0

**Comment by fredrikaverpil** [comment]
@hramezani out of curiosity, since you removed the additional arguments in your first commit, and I did too (but had failed tests), did you do something else?

**Comment by hramezani** [comment]
@fredrikaverpil I made the tests with `test="skip"` testable. for example, the first test was:

```py
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file='.env', env_file_encoding='utf-8')
```

It needed `BaseSettings` and `SettingsConfigDict` to be imported. So, I imprted them by:

`from pydantic_settings import BaseSettings, SettingsConfigDict`
