### ISSUE TITLE
Error parsing json string environment variable when using VSCode's debugger

### ISSUE THREAD

**Issue by dnsv** [pydantic/pydantic-settings#91]
**Description**

I'm using `BaseSettings` to parse an environment variable that's a json string with a newline character. The variable is being parsed differently when using VSCode's debugger. 

https://github.com/pydantic/pydantic-settings/assets/1542063/7bc5973f-1bf8-4112-b2ac-e2ec00439406

The json is invalid because of the way the string is being parsed differently.

**Example Code**

```python
# main.py
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    foo: dict

    class Config:
        env_file = ".env"

settings = Settings()

print(settings.foo)
```

```env
# .env
FOO='{"foo":"bar\nbaz"}'
```

**Python, Pydantic & OS Version**

pydantic version: 2.0a3
pydantic-core version: 0.25.0 release build profile
python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4-arm64-arm-64bit

I initially experienced this with Pydantic v1.10.9.

**Comment by hramezani** [comment]
Thanks for reporting this issue.

I've tested your provided example with the latest `pydantic-settings` beta and it was ok.

you can install it by `pip install pydantic-settings==2.0b2`

Please test it and let me know what is the result.

**Comment by dnsv** [comment]
Hi @hramezani. Thanks for looking into it. I tried the latest version and get the same result. As it's okay for you, I tried changing a few things that are specific to my environment, e.g. a completely new VSCode profile, a different Python version, etc. but I still get the same result. Do you maybe have a suggestions as to what else I could affect the result?

**Comment by hramezani** [comment]
@dnsv I didn't test it with the VSCode debugger. but based on your posted video, It seems your debugger uses `v2.0a1` which is the first alpha release of `pydantic-settings`.
