### ISSUE TITLE
Usage of `SettingsConfigDict` values in custom sources

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic-settings#98]
With `parse_env_var` removed in V2, I've tried implementing the same behavior with a custom source (as specified in the migration guide):

```python
class CustomEnvSettingsSource(EnvSettingsSource):

    def get_field_value(self, field: FieldInfo, field_name: str) -> Tuple[Any, str, bool]:
        env_val, field_key, value_is_complex = super().get_field_value(field, field_name)
        if field_key == "str_list":
            val = [issuer.strip() for issuer in env_val.split(",")]
        else:
            val = env_val
        return val, field_key, value_is_complex


class MySettings(BaseSettings):
    str_list: list[str]

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        custom_env_settings = CustomEnvSettingsSource(
            case_sensitive=settings_cls.model_config.get("case_sensitive"),
            env_prefix=settings_cls.model_config.get("env_prefix"),
            env_nested_delimiter=settings_cls.model_config.get("env_nested_delimiter"),
        )
        return init_settings, custom_env_settings, dotenv_settings, file_secret_settings
```

The first issue is that I have to manually pass the config values (`case_sensitive`, `env_prefix` and `env_nested_delimiter`) when instantiating `CustomEnvSettingsSource`.
The second one is that even with my current solution, it won't take into account the config values provided on instantiation (with a leading `_`).

I'll try to work on this when I have some time, it will require some refactoring and hopefully no breaking changes.

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
@Viicos what do you want to do?

> The first issue is that I have to manually pass the config values (case_sensitive, env_prefix and env_nested_delimiter) when instantiating CustomEnvSettingsSource.

You only need to pass the `settings_cls` which is available there. if you don't provide the other values, they will be taken from the config.

So this will work:

```py
class MySettings(BaseSettings):
    str_list: list[str]

    model_config = SettingsConfigDict(env_nested_delimiter='__')

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        custom_env_settings = CustomEnvSettingsSource(settings_cls)
        return init_settings, custom_env_settings, dotenv_settings, file_secret_settings
```

I didn't get what you are doing in `get_field_value` because you have the loaded value from env(string) in this method and the returned value of this method will be passed to `prepare_field_value`. Then parsing the `str` value to `list` happen in `prepare_field_value`.

**Comment by Viicos** [comment]
This is what I'm trying to accomplish:

```python
os.environ["str_list"] = "item1,item2"
settings = MySettings()
assert settings.str_list == ["item1", "item2"]

# or
os.environ["prefix_str_list"] = "item1,item2"
settings = MySettings(_env_prefix="prefix_")
assert settings.str_list == ["item1", "item2"]
```

> You only need to pass the `settings_cls` which is available there. if you don't provide the other values, they will be taken from the config.

The issue is that since https://github.com/pydantic/pydantic-settings/pull/76, the config values are determined in `BaseSettings`, and then sources are instantiated with those determined values:

https://github.com/pydantic/pydantic-settings/blob/107e8def2c0cc6d187bfdece1ab3200e26f3a908/pydantic_settings/main.py#L108-L128

Meaning my `CustomEnvSettingsSource` won't know about the config values provided at instantiation time (only the ones from `model_config` would be taken into account if specifying them explicitly when constructing `CustomEnvSettingsSource`).

---

I see two ways of fixing this issue:

<details><summary>First one, not ideal</summary>
<p>

What could be done is having some kind of context object storing all the config values (with values given at instantiation taken into account). That context object would be given to every source (instead of passing every config value one by one); e.g:

```python

class PydanticBaseEnvSettingsSource(PydanticBaseSettingsSource):
   # Before:
    def __init__(
        self, settings_cls: type[BaseSettings], case_sensitive: bool | None = None, env_prefix: str | None = None
    ) -> None:
        ...
    # After:
    def __init__(self, settings_cls: type[BaseSettings], config_context: ContextObj) -> None:
        ...
```

Then the signature of `settings_customise_sources` could be changed to have this context object:

```python
    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        context_obj: ContextObj,
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        # Here I'm able to give my custom source the context obj, so that it can use the correct config values
        return init_settings, CustomEnvSettingsSource(settings_cls, context_obj), dotenv_settings, file_secret_settings
```

And the [call made to `settings_customise_sources`](https://github.com/pydantic/pydantic-settings/blob/107e8def2c0cc6d187bfdece1ab3200e26f3a908/pydantic_settings/main.py#L141-L148) would be adapted as well.

This one isn't ideal because it introduces a breaking change regarding the modified signature.
</p>
</details> 

<details><summary>Second one, maybe better</summary>
<p>
Similar to the first one, maybe we could store that context object as an instance variable, and instead of giving the class to the sources, we would pass the settings instance, so that sources can read that context object from it. Still introduces breaking changes, but I don't think there're any other proper way of supporting this (as at some point we have to work with instances to get those config values provided at instantiation).
</p>
</details>

**Comment by hramezani** [comment]
The first one is possible with:

>os.environ["str_list"] = "item1,item2"
settings = MySettings()
assert settings.str_list == ["item1", "item2"]

```py
import os
from typing import Any, Tuple, Type

from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, EnvSettingsSource, PydanticBaseSettingsSource, SettingsConfigDict


class CustomEnvSettingsSource(EnvSettingsSource):
    def prepare_field_value(self, field_name: str, field: FieldInfo, value: Any, value_is_complex: bool) -> Any:
        if field_name == "str_list":
            value = value.split(",")

        return value

class MySettings(BaseSettings):
    str_list: list[str]

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        custom_env_settings = CustomEnvSettingsSource(settings_cls)
        return init_settings, custom_env_settings, dotenv_settings, file_secret_settings


os.environ["str_list"] = "item1,item2"
settings = MySettings()
assert settings.str_list == ["item1", "item2"]
```

**Comment by hramezani** [comment]
But for the second one, it needs a small fix that I will create a PR for that tomorrow

**Comment by hramezani** [comment]
I've created a PR. By merging this PR, your second example is possible by having `env_prefix` in the config.

```py
class CustomEnvSettingsSource(EnvSettingsSource):
    def prepare_field_value(self, field_name: str, field: FieldInfo, value: Any, value_is_complex: bool) -> Any:
        if field_name == "str_list":
            value = value.split(",")

        return value

class MySettings(BaseSettings):
    str_list: list[str]

    model_config = SettingsConfigDict(env_prefix="prefix_")

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        custom_env_settings = CustomEnvSettingsSource(settings_cls)
        return init_settings, custom_env_settings


os.environ["prefix_str_list"] = "item1,item2"
settings = MySettings()
assert settings.str_list == ["item1", "item2"]
```
